-- Lab Partner commercial orders, approval, processing and urgency pricing.
CREATE TABLE IF NOT EXISTS public.lab_partner_user_links (
  lab_organization_id uuid NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE,
  user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  partner_id uuid NOT NULL REFERENCES public.lab_partners(id) ON DELETE RESTRICT,
  created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (lab_organization_id,user_id)
);
CREATE TABLE IF NOT EXISTS public.lab_order_pricing_settings (
  lab_organization_id uuid PRIMARY KEY REFERENCES public.organizations(id) ON DELETE CASCADE,
  default_contract text NOT NULL DEFAULT 'General', urgent_window_hours integer NOT NULL DEFAULT 24 CHECK (urgent_window_hours >= 0),
  timezone text NOT NULL DEFAULT 'Europe/Bucharest' CHECK (timezone='Europe/Bucharest'), updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE TABLE IF NOT EXISTS public.lab_contract_pricing_defaults (
  lab_organization_id uuid NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE, contract text NOT NULL,
  urgent_percent numeric(7,2) NOT NULL DEFAULT 0 CHECK (urgent_percent >= 0), processing_amount numeric(14,2) NOT NULL DEFAULT 0 CHECK (processing_amount >= 0),
  PRIMARY KEY (lab_organization_id,contract)
);
ALTER TABLE public.lab_work_types ADD COLUMN IF NOT EXISTS processing_enabled boolean NOT NULL DEFAULT false;
ALTER TABLE public.lab_contract_work_prices ADD COLUMN IF NOT EXISTS urgent_percent_override numeric(7,2) CHECK (urgent_percent_override IS NULL OR urgent_percent_override >= 0), ADD COLUMN IF NOT EXISTS processing_amount_override numeric(14,2) CHECK (processing_amount_override IS NULL OR processing_amount_override >= 0);
ALTER TABLE public.lab_work_orders ADD COLUMN IF NOT EXISTS order_origin text NOT NULL DEFAULT 'internal' CHECK (order_origin IN ('doctor','lab_partner','internal')), ADD COLUMN IF NOT EXISTS partner_id uuid REFERENCES public.lab_partners(id), ADD COLUMN IF NOT EXISTS deadline_at timestamptz, ADD COLUMN IF NOT EXISTS approval_state text NOT NULL DEFAULT 'approved' CHECK (approval_state IN ('approved','pending','rejected')), ADD COLUMN IF NOT EXISTS approval_reviewed_at timestamptz, ADD COLUMN IF NOT EXISTS approval_reviewed_by_user_id uuid REFERENCES auth.users(id), ADD COLUMN IF NOT EXISTS approval_reason text;
UPDATE public.lab_work_orders SET order_origin='internal',approval_state='approved' WHERE order_origin IS NULL OR approval_state IS NULL;
CREATE TABLE IF NOT EXISTS public.lab_partner_work_order_items (
  lab_organization_id uuid NOT NULL, work_order_id bigint NOT NULL, line_no integer NOT NULL CHECK(line_no>0), work_type text NOT NULL, color text, quantity integer NOT NULL CHECK(quantity>0), processing_requested boolean NOT NULL DEFAULT false, note text,
  PRIMARY KEY(lab_organization_id,work_order_id,line_no), FOREIGN KEY(lab_organization_id,work_order_id) REFERENCES public.lab_work_orders(lab_organization_id,id) ON DELETE CASCADE
);
CREATE TABLE IF NOT EXISTS public.lab_partner_work_order_price_lines (
  lab_organization_id uuid NOT NULL, work_order_id bigint NOT NULL, line_no integer NOT NULL, contract text NOT NULL, base_unit_price numeric(14,2) NOT NULL, base_subtotal numeric(14,2) NOT NULL, processing_unit_amount numeric(14,2) NOT NULL, urgent_percent numeric(7,2) NOT NULL, urgency_surcharge numeric(14,2) NOT NULL, line_total numeric(14,2) NOT NULL, price_fixed_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY(lab_organization_id,work_order_id,line_no), FOREIGN KEY(lab_organization_id,work_order_id,line_no) REFERENCES public.lab_partner_work_order_items(lab_organization_id,work_order_id,line_no) ON DELETE CASCADE
);
CREATE TABLE IF NOT EXISTS public.lab_work_order_approval_events (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, lab_organization_id uuid NOT NULL, work_order_id bigint NOT NULL, state text NOT NULL CHECK(state IN ('pending','approved','rejected')), reason text, actor_user_id uuid, created_at timestamptz NOT NULL DEFAULT now(),
  FOREIGN KEY(lab_organization_id,work_order_id) REFERENCES public.lab_work_orders(lab_organization_id,id) ON DELETE CASCADE
);
CREATE OR REPLACE FUNCTION public.lab_partner_can_access_order(p_lab uuid,p_order bigint) RETURNS boolean LANGUAGE sql STABLE SECURITY DEFINER SET search_path=public AS $$
 SELECT EXISTS(SELECT 1 FROM public.lab_work_orders o JOIN public.lab_partner_user_links l ON l.lab_organization_id=o.lab_organization_id AND l.partner_id=o.partner_id WHERE o.lab_organization_id=p_lab AND o.id=p_order AND l.user_id=auth.uid()); $$;
CREATE OR REPLACE FUNCTION public.estimate_lab_partner_work_order_price(p_lab uuid,p_items jsonb,p_deadline_at timestamptz) RETURNS jsonb LANGUAGE plpgsql STABLE SECURITY DEFINER SET search_path=public AS $$
DECLARE v_partner uuid; v_name text; v_hours integer; v_urgent boolean; v_lines jsonb; v_total numeric;
BEGIN
 IF public.effective_lab_role(p_lab) NOT IN ('lab partner','lab_partner') THEN RAISE EXCEPTION 'Lab Partner access denied'; END IF;
 SELECT l.partner_id,p.name INTO v_partner,v_name FROM public.lab_partner_user_links l JOIN public.lab_partners p ON p.id=l.partner_id AND p.active WHERE l.lab_organization_id=p_lab AND l.user_id=auth.uid(); IF v_partner IS NULL THEN RAISE EXCEPTION 'Lab Partner mapping is missing'; END IF;
 SELECT urgent_window_hours INTO v_hours FROM public.lab_order_pricing_settings WHERE lab_organization_id=p_lab; v_hours:=coalesce(v_hours,24); v_urgent:=p_deadline_at < now() + make_interval(hours=>v_hours);
 WITH input AS (SELECT row_number() over() n,x FROM jsonb_array_elements(p_items) x), resolved AS (SELECT n,x,wt.tip_lucrare,coalesce(cp.pret,0) base,coalesce(cp.processing_amount_override,d.processing_amount,0) processing,coalesce(cp.urgent_percent_override,d.urgent_percent,0) urgent FROM input JOIN public.lab_work_types wt ON wt.lab_organization_id=p_lab AND wt.active AND lower(wt.tip_lucrare)=lower(x->>'work_type') LEFT JOIN LATERAL(SELECT * FROM public.lab_contract_work_prices z WHERE z.lab_organization_id=p_lab AND lower(z.tip_lucrare)=lower(wt.tip_lucrare) AND lower(z.contract) IN(lower(v_name),'general') ORDER BY CASE WHEN lower(z.contract)=lower(v_name) THEN 0 ELSE 1 END LIMIT 1) cp ON true LEFT JOIN public.lab_contract_pricing_defaults d ON d.lab_organization_id=p_lab AND lower(d.contract)=lower(coalesce(cp.contract,'General')))
 SELECT jsonb_agg(jsonb_build_object('line_no',n,'contract',coalesce((SELECT contract FROM public.lab_contract_work_prices z WHERE z.lab_organization_id=p_lab AND lower(z.tip_lucrare)=lower(tip_lucrare) LIMIT 1),'General'),'base_unit_price',base,'processing_unit_amount',processing,'urgent_percent',CASE WHEN v_urgent THEN urgent ELSE 0 END,'line_total',round((base+CASE WHEN coalesce((x->>'processing_requested')::boolean,false) THEN processing ELSE 0 END)*(x->>'quantity')::numeric*(1+CASE WHEN v_urgent THEN urgent ELSE 0 END/100),2)) ORDER BY n),coalesce(sum(round((base+CASE WHEN coalesce((x->>'processing_requested')::boolean,false) THEN processing ELSE 0 END)*(x->>'quantity')::numeric*(1+CASE WHEN v_urgent THEN urgent ELSE 0 END/100),2)),0) INTO v_lines,v_total FROM resolved;
 RETURN jsonb_build_object('urgent',v_urgent,'urgent_window_hours',v_hours,'lines',coalesce(v_lines,'[]'::jsonb),'final_price',v_total);
END $$;
CREATE OR REPLACE FUNCTION public.review_external_work_order(p_lab uuid,p_order bigint,p_decision text,p_reason text DEFAULT NULL) RETURNS boolean LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$
DECLARE v_state text:=lower(trim(p_decision)); BEGIN IF NOT public.is_lab_management(p_lab) THEN RAISE EXCEPTION 'Management access denied'; END IF; IF v_state NOT IN ('approve','reject') THEN RAISE EXCEPTION 'Invalid review decision'; END IF;
 UPDATE public.lab_work_orders SET approval_state=CASE WHEN v_state='approve' THEN 'approved' ELSE 'rejected' END,approval_reviewed_at=now(),approval_reviewed_by_user_id=auth.uid(),approval_reason=nullif(left(trim(coalesce(p_reason,'')),1000),'') WHERE lab_organization_id=p_lab AND id=p_order AND order_origin IN ('doctor','lab_partner') AND approval_state='pending'; IF NOT FOUND THEN RAISE EXCEPTION 'Order is not awaiting approval'; END IF;
 INSERT INTO public.lab_work_order_approval_events(lab_organization_id,work_order_id,state,reason,actor_user_id) VALUES(p_lab,p_order,CASE WHEN v_state='approve' THEN 'approved' ELSE 'rejected' END,nullif(left(trim(coalesce(p_reason,'')),1000),''),auth.uid()); RETURN true; END $$;
CREATE OR REPLACE FUNCTION public.create_lab_partner_work_order(p_lab uuid,p_deadline_at timestamptz,p_items jsonb,p_note text DEFAULT NULL) RETURNS bigint LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$
DECLARE v_id bigint; v_partner uuid; v_name text; v_estimate jsonb; BEGIN
 IF public.effective_lab_role(p_lab) NOT IN ('lab partner','lab_partner') THEN RAISE EXCEPTION 'Lab Partner access denied'; END IF;
 SELECT l.partner_id,p.name INTO v_partner,v_name FROM public.lab_partner_user_links l JOIN public.lab_partners p ON p.id=l.partner_id AND p.active WHERE l.lab_organization_id=p_lab AND l.user_id=auth.uid(); IF v_partner IS NULL OR p_deadline_at IS NULL OR p_deadline_at<=now() OR jsonb_array_length(coalesce(p_items,'[]'))=0 THEN RAISE EXCEPTION 'Invalid Lab Partner order'; END IF;
 v_id:=public.next_lab_work_order_id(p_lab); v_estimate:=public.estimate_lab_partner_work_order_price(p_lab,p_items,p_deadline_at);
 INSERT INTO public.lab_work_orders(lab_organization_id,id,deadline,deadline_at,status,nume_partener,partner_id,contract,order_origin,approval_state,created_by_user_id,created_at,updated_by_user_id,updated_at,data_receptie,snapshot_list_price,snapshot_final_price,price_source,price_fixed_at) VALUES(p_lab,v_id,(p_deadline_at AT TIME ZONE 'Europe/Bucharest')::date,p_deadline_at,'Not Started',v_name,v_partner,coalesce((v_estimate->'lines'->0->>'contract'),'General'),'lab_partner','pending',public.current_legacy_user_id(),now(),public.current_legacy_user_id(),now(),now(),(v_estimate->>'final_price')::numeric,(v_estimate->>'final_price')::numeric,'lab_partner_snapshot',now());
 INSERT INTO public.lab_partner_work_order_items(lab_organization_id,work_order_id,line_no,work_type,color,quantity,processing_requested,note) SELECT p_lab,v_id,row_number() over(),trim(x->>'work_type'),nullif(left(trim(coalesce(x->>'color','')),120),''),(x->>'quantity')::integer,coalesce((x->>'processing_requested')::boolean,false),CASE WHEN row_number() over()=1 THEN nullif(left(trim(coalesce(p_note,'')),2000),'') END FROM jsonb_array_elements(p_items) x;
 INSERT INTO public.lab_work_order_approval_events(lab_organization_id,work_order_id,state,actor_user_id) VALUES(p_lab,v_id,'pending',auth.uid()); RETURN v_id; END $$;
