-- Flowrise Admin storage monitoring and scoped cleanup.
-- Apply before deploying the Edge Functions and frontend.
-- This migration prepares cleanup; it does not delete selected work orders.
BEGIN;
SET LOCAL check_function_bodies = off;

-- Source: db/schema/10_tables/32_admin_cleanup.sql
-- Durable Admin cleanup selections; no patient or financial payload snapshots.
ALTER TABLE public.lab_work_orders
 ADD COLUMN IF NOT EXISTS cleanup_revision bigint NOT NULL DEFAULT 0,
 ADD COLUMN IF NOT EXISTS clinical_cleanup_generation bigint NOT NULL DEFAULT 0,
 ADD COLUMN IF NOT EXISTS clinical_cleared_at timestamptz;
CREATE TABLE IF NOT EXISTS public.admin_cleanup_jobs(
 id uuid PRIMARY KEY DEFAULT gen_random_uuid(), lab_organization_id uuid NOT NULL REFERENCES public.organizations(id),
 created_by uuid NOT NULL, action text NOT NULL CHECK(action IN ('files','clinical','all')),
 date_from date NOT NULL,date_to date NOT NULL CHECK(date_to>=date_from),
 state text NOT NULL DEFAULT 'preview' CHECK(state IN ('preview','running','awaiting_uploads','completed','partial','failed','expired')),
 created_at timestamptz NOT NULL DEFAULT now(), expires_at timestamptz NOT NULL DEFAULT now()+interval '15 minutes',
 confirmed_at timestamptz,reconcile_after timestamptz,updated_at timestamptz NOT NULL DEFAULT now(),
 missing_dates_count integer NOT NULL DEFAULT 0
);
CREATE TABLE IF NOT EXISTS public.admin_cleanup_items(
 id uuid PRIMARY KEY DEFAULT gen_random_uuid(),job_id uuid NOT NULL REFERENCES public.admin_cleanup_jobs(id) ON DELETE CASCADE,
 order_id bigint NOT NULL,revision bigint NOT NULL,
 state text NOT NULL DEFAULT 'pending' CHECK(state IN ('pending','processing','awaiting_uploads','completed','skipped','failed')),
 counts jsonb NOT NULL DEFAULT '{}',bytes bigint NOT NULL DEFAULT 0,worker_id uuid,lease_until timestamptz,
 error_code text,error_message text,initial_finished boolean NOT NULL DEFAULT false,
 UNIQUE(job_id,order_id)
);
CREATE TABLE IF NOT EXISTS public.admin_cleanup_files(
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,item_id uuid NOT NULL REFERENCES public.admin_cleanup_items(id) ON DELETE CASCADE,
 bucket text NOT NULL CHECK(bucket='work-order-files'),object_path text NOT NULL,metadata_id uuid,
 size_bytes bigint,object_version text,initial_done boolean NOT NULL DEFAULT false,reconciled boolean NOT NULL DEFAULT false,
 UNIQUE(item_id,bucket,object_path)
);
CREATE TABLE IF NOT EXISTS public.lab_work_order_id_watermarks(
 lab_organization_id uuid PRIMARY KEY REFERENCES public.organizations(id),maximum_id bigint NOT NULL
);
INSERT INTO public.lab_work_order_id_watermarks SELECT lab_organization_id,max(id) FROM public.lab_work_orders GROUP BY lab_organization_id
ON CONFLICT(lab_organization_id) DO UPDATE SET maximum_id=greatest(lab_work_order_id_watermarks.maximum_id,excluded.maximum_id);
ALTER TABLE public.admin_cleanup_jobs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.admin_cleanup_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.admin_cleanup_files ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.lab_work_order_id_watermarks ENABLE ROW LEVEL SECURITY;
CREATE INDEX IF NOT EXISTS admin_cleanup_jobs_due_idx ON public.admin_cleanup_jobs(state,reconcile_after,created_at);
CREATE INDEX IF NOT EXISTS admin_cleanup_items_job_idx ON public.admin_cleanup_items(job_id,state,order_id);
CREATE INDEX IF NOT EXISTS admin_cleanup_items_order_idx ON public.admin_cleanup_items(order_id,state);

ALTER TABLE public.admin_cleanup_files ADD COLUMN IF NOT EXISTS object_version text;

-- Source: db/schema/20_functions/next_lab_work_order_id.sql
-- Flowrise Supabase function: public.next_lab_work_order_id(p_lab_organization_id uuid)
-- Generated from the Supabase schema snapshot dated 2026-09-04.
-- The complete CREATE OR REPLACE FUNCTION definition follows.

CREATE OR REPLACE FUNCTION public.next_lab_work_order_id(p_lab_organization_id uuid)
 RETURNS bigint
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
declare
    v_next bigint;
begin
    perform pg_advisory_xact_lock(hashtext('flowrise-work-order-' || p_lab_organization_id::text));

    select greatest(coalesce(max(wo.id),0),coalesce((select maximum_id from public.lab_work_order_id_watermarks where lab_organization_id=p_lab_organization_id),0)) + 1
      into v_next
    from public.lab_work_orders wo
    where wo.lab_organization_id = p_lab_organization_id;

    return v_next;
end;
$function$
;

-- Security definer: True
-- Return type: bigint
-- Identity arguments: p_lab_organization_id uuid

-- Source: db/schema/20_functions/save_work_order_clinical_case.sql
-- Canonical connection list. Absence of an edge means solo for that pair.
-- Explicit writes reject endpoints outside scope; retained links are pruned after scope edits.
CREATE OR REPLACE FUNCTION public.normalize_tooth_connections(p_connections jsonb,p_teeth integer[],p_strict boolean DEFAULT true)
RETURNS jsonb LANGUAGE plpgsql IMMUTABLE SET search_path=public AS $$
DECLARE
    v_arch integer[]:=ARRAY[18,17,16,15,14,13,12,11,21,22,23,24,25,26,27,28,48,47,46,45,44,43,42,41,31,32,33,34,35,36,37,38];
    v_pair jsonb; v_a integer; v_b integer; v_i integer; v_j integer;
    v_indices integer[]:='{}'; v_result jsonb:='[]';
BEGIN
    IF jsonb_typeof(p_connections) IS DISTINCT FROM 'array' THEN
        RAISE EXCEPTION 'Tooth connections must be an array of adjacent FDI pairs';
    END IF;
    FOR v_pair IN SELECT value FROM jsonb_array_elements(p_connections) LOOP
        IF jsonb_typeof(v_pair) IS DISTINCT FROM 'array' THEN RAISE EXCEPTION 'Invalid tooth connection pair'; END IF;
        IF jsonb_array_length(v_pair)<>2 OR jsonb_typeof(v_pair->0)<>'number' OR jsonb_typeof(v_pair->1)<>'number' THEN
            RAISE EXCEPTION 'Tooth connection endpoints must be two FDI integers';
        END IF;
        IF (v_pair->>0)::numeric<>trunc((v_pair->>0)::numeric) OR (v_pair->>1)::numeric<>trunc((v_pair->>1)::numeric) THEN
            RAISE EXCEPTION 'Tooth connection endpoints must be integers';
        END IF;
        v_a:=(v_pair->>0)::integer; v_b:=(v_pair->>1)::integer;
        v_i:=array_position(v_arch,v_a); v_j:=array_position(v_arch,v_b);
        IF v_i IS NULL OR v_j IS NULL OR abs(v_i-v_j)<>1 OR least(v_i,v_j)=16 THEN
            RAISE EXCEPTION 'Only adjacent teeth in the same arch can be connected';
        END IF;
        IF NOT (v_a=ANY(coalesce(p_teeth,'{}')) AND v_b=ANY(coalesce(p_teeth,'{}'))) THEN
            IF p_strict THEN RAISE EXCEPTION 'Both connected teeth must belong to the Work Order'; END IF;
            CONTINUE;
        END IF;
        v_indices:=array_append(v_indices,least(v_i,v_j));
    END LOOP;
    FOR v_i IN SELECT DISTINCT n FROM unnest(v_indices) n ORDER BY n LOOP
        v_result:=v_result||jsonb_build_array(jsonb_build_array(v_arch[v_i],v_arch[v_i+1]));
    END LOOP;
    RETURN v_result;
END; $$;
REVOKE ALL ON FUNCTION public.normalize_tooth_connections(jsonb,integer[],boolean) FROM public,authenticated;

-- Internal writer shared by all atomic role RPCs. Tooth scope always comes from items.
CREATE OR REPLACE FUNCTION public.save_work_order_clinical_case(p_lab uuid,p_order_id bigint,p_case jsonb DEFAULT '{}'::jsonb)
RETURNS bigint LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$
DECLARE
    v_order public.lab_work_orders%rowtype;
    v_id bigint;
    v_case public.lab_patient_cases%rowtype;
    v_details jsonb;
    v_teeth text;
    v_case_metadata jsonb;
    v_key text;
    v_existing_details jsonb;
    v_scope integer[];
    v_explicit_connections boolean;
BEGIN
    p_case:=coalesce(p_case,'{}'::jsonb);
    IF jsonb_typeof(p_case)<>'object' THEN RAISE EXCEPTION 'Clinical case must be an object'; END IF;
    FOR v_key IN SELECT jsonb_object_keys(p_case) LOOP
        IF v_key NOT IN ('tooth_details','tooth_details_json','clinic_note','shade','method','production_notes','expected_cleanup_revision') THEN
            RAISE EXCEPTION 'Unsupported clinical case field: %',v_key;
        END IF;
        IF v_key IN ('clinic_note','shade','method','production_notes') AND jsonb_typeof(p_case->v_key) NOT IN ('string','null') THEN
            RAISE EXCEPTION 'Clinical case field % must be text',v_key;
        END IF;
    END LOOP;
    IF p_case ? 'tooth_details' AND p_case ? 'tooth_details_json' THEN
        RAISE EXCEPTION 'Supply tooth_details or tooth_details_json, not both';
    END IF;
    SELECT * INTO v_order FROM public.lab_work_orders
    WHERE lab_organization_id=p_lab AND id=p_order_id FOR UPDATE;
    IF NOT FOUND THEN RAISE EXCEPTION 'Work Order not found'; END IF;
    -- The cleanup generation is stable during compound item/order saves.
    -- An aggregate mutation revision would change before this internal writer runs.
    IF v_order.clinical_cleanup_generation>0 THEN
        IF p_case='{}'::jsonb AND v_order.nume_pacient IS NULL THEN RETURN NULL; END IF;
        IF coalesce(p_case->>'expected_cleanup_revision','')<>v_order.clinical_cleanup_generation::text THEN
            RAISE EXCEPTION 'Clinical case changed after cleanup. Reload the Work Order.';
        END IF;
    END IF;
    SELECT * INTO v_case FROM public.lab_patient_cases
    WHERE lab_organization_id=p_lab AND work_order_id=p_order_id ORDER BY id LIMIT 1;
    v_id:=v_case.id;
    IF v_id IS NULL THEN
        v_id:=p_order_id;
        IF EXISTS(SELECT 1 FROM public.lab_patient_cases WHERE lab_organization_id=p_lab AND id=v_id) THEN
            SELECT coalesce(max(id),0)+1 INTO v_id FROM public.lab_patient_cases WHERE lab_organization_id=p_lab;
        END IF;
    END IF;
    v_existing_details:=public.sanitize_tooth_details(coalesce(nullif(v_case.tooth_details_json,'')::jsonb,'{}'::jsonb));
    v_details:=public.sanitize_tooth_details(coalesce(
        p_case->'tooth_details',
        CASE WHEN jsonb_typeof(p_case->'tooth_details_json')='string' THEN (p_case->>'tooth_details_json')::jsonb
             ELSE p_case->'tooth_details_json' END,
        nullif(v_case.tooth_details_json,'')::jsonb,'{}'::jsonb));
    IF jsonb_typeof(v_details)<>'object' THEN RAISE EXCEPTION 'Tooth details must be an object'; END IF;
    IF EXISTS(SELECT 1 FROM jsonb_each(v_details) d
        WHERE (d.key<>'__case' AND d.key !~ '^[1-4][1-8]$') OR jsonb_typeof(d.value)<>'object') THEN
        RAISE EXCEPTION 'Tooth details must map FDI numbers or __case to objects';
    END IF;
    v_explicit_connections:=coalesce(v_details->'__case' ? 'tooth_connections',false)
        AND (p_case ? 'tooth_details' OR p_case ? 'tooth_details_json');
    -- Omitted metadata is retained for older clients and partial AI edits.
    v_case_metadata:=coalesce(v_existing_details->'__case','{}'::jsonb)||coalesce(v_details->'__case','{}'::jsonb);
    SELECT coalesce(array_agg(tooth_number),'{}') INTO v_scope FROM public.lab_work_order_items
    WHERE lab_organization_id=p_lab AND work_order_id=p_order_id;
    v_case_metadata:=v_case_metadata||jsonb_build_object('tooth_connections',public.normalize_tooth_connections(
        coalesce(v_case_metadata->'tooth_connections','[]'::jsonb),v_scope,v_explicit_connections));
    -- Discard stale tooth entries and overwrite clinical work types with canonical scope.
    SELECT coalesce(jsonb_object_agg(i.tooth_number::text,
        coalesce(v_existing_details->i.tooth_number::text,'{}'::jsonb)||coalesce(v_details->i.tooth_number::text,'{}'::jsonb)||jsonb_build_object('work_type',i.work_type,'type',i.work_type)),'{}'::jsonb),
        string_agg(i.tooth_number::text,',' ORDER BY i.tooth_number)
    INTO v_details,v_teeth FROM public.lab_work_order_items i
    WHERE i.lab_organization_id=p_lab AND i.work_order_id=p_order_id;
    IF v_case_metadata<>'{}'::jsonb THEN v_details:=v_details||jsonb_build_object('__case',v_case_metadata); END IF;
    INSERT INTO public.lab_patient_cases(lab_organization_id,id,work_order_id,nume_pacient,nume_partener,
        deadline,selected_teeth,tooth_details_json,shade,method,clinic_note,production_notes,
        created_by_user_id,created_at,updated_by_user_id,updated_at)
    VALUES(p_lab,v_id,p_order_id,v_order.nume_pacient,v_order.nume_partener,v_order.deadline,v_teeth,v_details::text,
        coalesce(p_case->>'shade',v_case.shade),coalesce(p_case->>'method',v_case.method),
        coalesce(p_case->>'clinic_note',v_case.clinic_note),
        CASE WHEN public.is_lab_management(p_lab) THEN coalesce(p_case->>'production_notes',v_case.production_notes) ELSE v_case.production_notes END,
        public.current_legacy_user_id(),now(),public.current_legacy_user_id(),now())
    ON CONFLICT(lab_organization_id,id) DO UPDATE SET
        nume_pacient=excluded.nume_pacient,nume_partener=excluded.nume_partener,deadline=excluded.deadline,
        selected_teeth=excluded.selected_teeth,tooth_details_json=excluded.tooth_details_json,
        shade=excluded.shade,method=excluded.method,clinic_note=excluded.clinic_note,production_notes=excluded.production_notes,
        updated_by_user_id=excluded.updated_by_user_id,updated_at=excluded.updated_at;
    IF v_order.clinical_cleared_at IS NOT NULL THEN
        UPDATE public.lab_work_orders SET clinical_cleared_at=NULL WHERE lab_organization_id=p_lab AND id=p_order_id;
    END IF;
    RETURN v_id;
END; $$;
REVOKE ALL ON FUNCTION public.save_work_order_clinical_case(uuid,bigint,jsonb) FROM public,authenticated;

-- Source: db/schema/20_functions/get_work_orders_page.sql
-- Bounded dashboard read. The materialized date/role scope precedes item and cost work.
-- Absent reception boundaries default to today-89/today in Europe/Bucharest;
-- explicit JSON null disables each boundary. All date endpoints are inclusive.
-- Facets use date/role/hide-old/maximum-id scope before text/column selections.
-- Summary covers every filtered row, independent of LIMIT/OFFSET. Unknown prices
-- or authorized stage amounts keep the corresponding financial total NULL.
-- v188 row fields retain their existing masks. salary_stages adds only the
-- current technician's assignment history (the legacy get_my_salary shape).
-- selected_technician_cost is management's chosen technician amount or the
-- current technician's own active assignments; other roles always receive NULL.
-- Nonempty unsupported column filters and invalid sorts are rejected.
-- maximum_id can anchor a multi-request export against later inserts; it is
-- not a transactional snapshot of edits/deletions between requests.
CREATE OR REPLACE FUNCTION public.get_work_orders_page(p_lab_organization_id uuid,p_filters jsonb DEFAULT '{}'::jsonb,p_limit integer DEFAULT 100,p_offset integer DEFAULT 0)
RETURNS jsonb LANGUAGE plpgsql STABLE SECURITY DEFINER SET search_path=public AS $function$
DECLARE
 mg boolean:=public.is_lab_management(p_lab_organization_id);
 dash boolean:=public.is_lab_dashboard(p_lab_organization_id);
 tech boolean:=public.is_lab_technician(p_lab_organization_id);
 doc boolean:=public.is_connected_doctor_for_lab(p_lab_organization_id);
 tech_name text:=lower(trim(coalesce(public.current_technician_name(),'')));
 today date:=(now() AT TIME ZONE 'Europe/Bucharest')::date;
 rf date; rt date; df date; dt date; uf date; ut date;
 k text; val text; pair text[]; columns_map jsonb:='{"id": "id", "status": "status", "patient": "nume_pacient", "partner": "nume_partener", "contract": "contract", "workType": "work_type_summary", "elements": "element_count", "listPrice": "list_price", "discount": "discount", "finalPrice": "final_price", "modelTech": "tehnician_model", "statusModel": "status_model", "modelingTech": "tehnician1_modelare", "statusModeling": "status_modelare", "ceramicTech": "tehnician2_cer_fin", "statusCerFin": "status_cer_fin", "deadline": "deadline", "receptionDate": "reception_date", "lastUpdate": "updated_at", "ownCost": "own_cost", "selectedCost": "selected_technician_cost", "stages": "own_stages"}'::jsonb;
 sort_col text; sort_dir text; predicates text:='true'; result jsonb;
 numeric_keys text[]:=ARRAY['id','elements','listPrice','discount','finalPrice','ownCost','selectedCost'];
 match text[];
BEGIN
 IF NOT coalesce(mg OR dash OR tech OR doc,false) THEN RAISE EXCEPTION 'Access denied'; END IF;
 p_filters:=coalesce(p_filters,'{}'::jsonb);
 IF jsonb_typeof(p_filters)<>'object' THEN RAISE EXCEPTION 'Filters must be an object'; END IF;
 IF coalesce(p_filters->>'technician','')<>'' AND NOT coalesce(mg OR tech OR dash,false) THEN RAISE EXCEPTION 'Access denied'; END IF;
 IF p_limit IS NULL OR p_limit<1 OR p_offset IS NULL OR p_offset<0 THEN RAISE EXCEPTION 'Invalid pagination'; END IF;
 p_limit:=least(p_limit,200);
 FOREACH k IN ARRAY ARRAY['reception_from','reception_to','deadline_from','deadline_to','last_update_from','last_update_to'] LOOP
  val:=p_filters->>k;
  IF val IS NOT NULL THEN
   IF val !~ '^\d{4}-\d{2}-\d{2}$' THEN RAISE EXCEPTION 'Invalid date for %',k; END IF;
   PERFORM val::date;
  END IF;
 END LOOP;
 rf:=CASE WHEN p_filters?'reception_from' THEN (p_filters->>'reception_from')::date ELSE today-89 END;
 rt:=CASE WHEN p_filters?'reception_to' THEN (p_filters->>'reception_to')::date ELSE today END;
 df:=(p_filters->>'deadline_from')::date; dt:=(p_filters->>'deadline_to')::date;
 uf:=(p_filters->>'last_update_from')::date; ut:=(p_filters->>'last_update_to')::date;
 IF rf>rt OR df>dt OR uf>ut THEN RAISE EXCEPTION 'Date range is reversed'; END IF;
 IF p_filters?'hide_old' AND jsonb_typeof(p_filters->'hide_old') NOT IN ('boolean','null') THEN RAISE EXCEPTION 'hide_old must be boolean'; END IF;
 IF p_filters?'status_in' AND jsonb_typeof(p_filters->'status_in')<>'array' THEN RAISE EXCEPTION 'status_in must be an array'; END IF;
 IF p_filters?'work_order_id' AND ((p_filters->>'work_order_id')::bigint IS NULL OR (p_filters->>'work_order_id')::bigint<1) THEN RAISE EXCEPTION 'Invalid work order id'; END IF;
 IF p_filters?'maximum_id' THEN PERFORM (p_filters->>'maximum_id')::bigint; END IF;
 sort_col:=columns_map->>coalesce(p_filters->>'sort_key','id');
 sort_dir:=lower(coalesce(p_filters->>'sort_dir','desc'));
 IF sort_col IS NULL OR sort_dir NOT IN ('asc','desc') THEN RAISE EXCEPTION 'Invalid sort'; END IF;
 IF p_filters?'columns' AND jsonb_typeof(p_filters->'columns')<>'object' THEN RAISE EXCEPTION 'columns must be an object'; END IF;
 FOR k,val IN SELECT key,value FROM jsonb_each_text(coalesce(p_filters->'columns','{}'::jsonb)) LOOP
  IF coalesce(trim(val),'')='' THEN CONTINUE; END IF;
  IF NOT columns_map?k THEN RAISE EXCEPTION 'Unsupported column filter: %',k; END IF;
  match:=regexp_match(trim(val),'^(>=|<=|>|<|=)\s*(-?\d+(\.\d+)?)$');
  IF k=ANY(numeric_keys) AND match IS NOT NULL THEN
   predicates:=predicates||format(' AND coalesce(%I,0) %s %L::numeric',columns_map->>k,match[1],match[2]);
  ELSE
   predicates:=predicates||format(' AND strpos(lower(coalesce(%I::text,'''') ),lower(%L))>0',columns_map->>k,trim(val));
  END IF;
 END LOOP;
 EXECUTE format($query$
 WITH base AS MATERIALIZED (
  SELECT wo.* FROM public.lab_work_orders wo
  WHERE wo.lab_organization_id=$1 AND wo.archived_at IS NULL
   AND (NOT $2?'work_order_id' OR wo.id=($2->>'work_order_id')::bigint)
   AND ($3 OR $4 OR ($5 AND $7 IN (lower(trim(coalesce(wo.tehnician_model,''))),lower(trim(coalesce(wo.tehnician1_modelare,''))),lower(trim(coalesce(wo.tehnician2_cer_fin,'')))) ) OR ($6 AND public.doctor_matches_partner(wo.nume_partener)))
   AND ($8 IS NULL OR coalesce(wo.data_receptie,wo.created_at)>=($8::timestamp AT TIME ZONE 'Europe/Bucharest'))
   AND ($9 IS NULL OR coalesce(wo.data_receptie,wo.created_at)<(($9+1)::timestamp AT TIME ZONE 'Europe/Bucharest'))
   AND ($10 IS NULL OR wo.deadline >= $10) AND ($11 IS NULL OR wo.deadline <= $11)
   AND ($12 IS NULL OR wo.updated_at>=($12::timestamp AT TIME ZONE 'Europe/Bucharest'))
   AND ($13 IS NULL OR wo.updated_at<(($13+1)::timestamp AT TIME ZONE 'Europe/Bucharest'))
   AND (NOT coalesce(($2->>'hide_old')::boolean,false) OR NOT coalesce(wo.deadline<$14 AND wo.status IN ('Finished','Shipped','List Sent','Paid'),false))
   AND (NOT $2?'status_in' OR wo.status IN (SELECT jsonb_array_elements_text($2->'status_in')))
   AND ($2->>'maximum_id' IS NULL OR wo.id<=($2->>'maximum_id')::bigint)
 ), clinical AS MATERIALIZED (
  SELECT b.*,i.work_types,i.work_type_summary,i.element_count FROM base b
  CROSS JOIN LATERAL (
   SELECT coalesce(array_agg(t.work_type ORDER BY t.first_tooth,t.work_type),ARRAY[]::text[]) work_types,
    string_agg(t.work_type,' / ' ORDER BY t.first_tooth,t.work_type) work_type_summary,coalesce(sum(t.n),0) element_count
   FROM (SELECT work_type,min(tooth_number) first_tooth,count(*) n FROM public.lab_work_order_items WHERE lab_organization_id=$1 AND work_order_id=b.id GROUP BY work_type) t
  ) i
 ), selected AS MATERIALIZED (
  SELECT * FROM clinical b WHERE
   (coalesce($2->>'status','')='' OR b.status=$2->>'status')
   AND (coalesce($2->>'partner','')='' OR b.nume_partener=$2->>'partner')
   AND (coalesce($2->>'patient','')='' OR strpos(lower(coalesce(b.nume_pacient,'')),lower($2->>'patient'))>0)
   AND (coalesce($2->>'work_type','')='' OR ($2->>'work_type')=ANY(b.work_types))
   AND (coalesce($2->>'technician','')='' OR lower(trim($2->>'technician')) IN (lower(trim(b.tehnician_model)),lower(trim(b.tehnician1_modelare)),lower(trim(b.tehnician2_cer_fin))))
   AND (coalesce($2->>'search','')='' OR strpos(lower(concat_ws(' ',b.id,b.nume_pacient,b.nume_partener,b.status,b.work_type_summary)),lower($2->>'search'))>0)
 ), masked AS MATERIALIZED (
  SELECT b.id,
   b.deadline,
   b.status,
   b.nume_pacient,
   b.nume_partener,
   b.data_receptie,
   b.locked,
   b.status_model,
   b.status_modelare,
   b.status_cer_fin,
   b.created_at,
   b.updated_at,b.clinical_cleared_at,b.clinical_cleanup_generation,b.cleanup_revision,
   b.model_not_applicable,
   b.modelare_not_applicable,
   b.cer_fin_not_applicable,
   CASE WHEN $3 OR $4 OR $5 THEN b.tehnician_model END tehnician_model,
   CASE WHEN $3 OR $4 OR $5 THEN b.tehnician1_modelare END tehnician1_modelare,
   CASE WHEN $3 OR $4 OR $5 THEN b.tehnician2_cer_fin END tehnician2_cer_fin,
   CASE WHEN $3 THEN b.contract END contract,
   CASE WHEN $3 THEN b.discount END discount,
   CASE WHEN $3 THEN b.created_by_user_id END created_by_user_id,
   CASE WHEN $3 THEN b.updated_by_user_id END updated_by_user_id,
   b.work_types,b.work_type_summary,b.element_count,coalesce(b.data_receptie,b.created_at) reception_date,
   CASE WHEN $3 OR $6 THEN b.snapshot_list_price END list_price,
   CASE WHEN $3 OR $6 THEN b.snapshot_final_price END final_price,
   CASE WHEN $3 THEN costs.cost_model END cost_model,
   CASE WHEN $3 THEN costs.cost_modelare END cost_modelare,
   CASE WHEN $3 THEN costs.cost_cer_fin END cost_cer_fin,
   costs.cost_model own_cost_model,costs.cost_modelare own_cost_modelare,costs.cost_cer_fin own_cost_cer_fin,
   salary.own_cost,salary.own_stages,
   costs.selected_technician_cost,costs.unknown_model,costs.unknown_modelare,costs.unknown_cer_fin,costs.unknown_selected
  FROM selected b
  CROSS JOIN LATERAL (
   SELECT coalesce(bool_or(amount IS NULL) FILTER(WHERE stage_key='model'),false) unknown_model,
    coalesce(bool_or(amount IS NULL) FILTER(WHERE stage_key='modelare'),false) unknown_modelare,
    coalesce(bool_or(amount IS NULL) FILTER(WHERE stage_key='cer_fin'),false) unknown_cer_fin,
    coalesce(bool_or(amount IS NULL) FILTER(WHERE chosen),false) unknown_selected,
    CASE WHEN bool_and(amount IS NOT NULL) FILTER(WHERE stage_key='model') THEN sum(amount) FILTER(WHERE stage_key='model') END cost_model,
    CASE WHEN bool_and(amount IS NOT NULL) FILTER(WHERE stage_key='modelare') THEN sum(amount) FILTER(WHERE stage_key='modelare') END cost_modelare,
    CASE WHEN bool_and(amount IS NOT NULL) FILTER(WHERE stage_key='cer_fin') THEN sum(amount) FILTER(WHERE stage_key='cer_fin') END cost_cer_fin,
    CASE WHEN bool_and(amount IS NOT NULL) FILTER(WHERE chosen) THEN sum(amount) FILTER(WHERE chosen) END selected_technician_cost
   FROM (SELECT a.stage_key,public.assignment_agreed_amount(a.id) amount,
    ($5 AND NOT $3 OR lower(trim(a.technician_name))=lower(trim($2->>'technician'))) chosen
    FROM public.lab_work_order_stage_assignments a WHERE a.lab_organization_id=$1 AND a.work_order_id=b.id AND a.ended_at IS NULL
     AND ($3 OR ($5 AND (a.technician_user_id=auth.uid() OR (a.technician_user_id IS NULL AND lower(trim(a.technician_name))=$7))))) amounts
  ) costs
  CROSS JOIN LATERAL (
   SELECT CASE WHEN $5 THEN CASE WHEN count(*)=0 THEN 0 WHEN bool_and(amount IS NOT NULL) THEN sum(amount) END END own_cost,
    string_agg(concat_ws(' ',stage_label,stage_status,payment_status),' ' ORDER BY started_at DESC) own_stages
   FROM (
    SELECT public.assignment_agreed_amount(a.id) amount,a.started_at,
     CASE a.stage_key WHEN 'model' THEN 'Model' WHEN 'modelare' THEN 'Modelare' ELSE 'Cer / Fin' END stage_label,
     CASE a.stage_key WHEN 'model' THEN coalesce(b.status_model,'Not Started') WHEN 'modelare' THEN coalesce(b.status_modelare,'Not Started') ELSE coalesce(b.status_cer_fin,'Not Started') END stage_status,
     CASE WHEN ($2->>'sort_key'='stages' OR coalesce($2->'columns'->>'stages','')<>'') THEN
      CASE WHEN public.assignment_agreed_amount(a.id) IS NOT NULL AND coalesce((SELECT sum(amount) FROM public.technician_payments WHERE assignment_id=a.id),0)>=public.assignment_agreed_amount(a.id) THEN 'Paid' ELSE 'Not Paid' END END payment_status
    FROM public.lab_work_order_stage_assignments a
    WHERE $5 AND a.lab_organization_id=$1 AND a.work_order_id=b.id
     AND (a.technician_user_id=auth.uid() OR (a.technician_user_id IS NULL AND lower(trim(a.technician_name))=$7))
   ) mine
  ) salary
 ), filtered AS MATERIALIZED (SELECT * FROM masked WHERE %s),
 page AS MATERIALIZED (SELECT * FROM filtered ORDER BY %I %s NULLS LAST,id DESC LIMIT $15 OFFSET $16),
 details AS (
  SELECT to_jsonb(p)-'own_cost_model'-'own_cost_modelare'-'own_cost_cer_fin'-'reception_date'-'unknown_model'-'unknown_modelare'-'unknown_cer_fin'-'unknown_selected'-'own_stages'
   ||jsonb_build_object('clinical_cleared_at',p.clinical_cleared_at,'clinical_cleanup_generation',p.clinical_cleanup_generation::text,'cleanup_revision',p.cleanup_revision::text,'items',scope.items,
    'paid_model',CASE WHEN $3 THEN public.work_order_stage_payment_status($1,p.id,'model') END,
    'paid_modelare',CASE WHEN $3 THEN public.work_order_stage_payment_status($1,p.id,'modelare') END,
    'paid_cer_fin',CASE WHEN $3 THEN public.work_order_stage_payment_status($1,p.id,'cer_fin') END,
    'salary_stages',CASE WHEN $5 THEN (SELECT coalesce(jsonb_agg(jsonb_build_object(
      'work_order_id',a.work_order_id,'stage_key',CASE a.stage_key WHEN 'model' THEN 'Model' WHEN 'modelare' THEN 'Modelare' ELSE 'Cer_Fin' END,
      'stage_label',CASE a.stage_key WHEN 'model' THEN 'Model' WHEN 'modelare' THEN 'Modelare' ELSE 'Cer / Fin' END,
      'stage_status',CASE a.stage_key WHEN 'model' THEN coalesce(p.status_model,'Not Started') WHEN 'modelare' THEN coalesce(p.status_modelare,'Not Started') ELSE coalesce(p.status_cer_fin,'Not Started') END,
      'payment_status',CASE WHEN public.assignment_agreed_amount(a.id) IS NOT NULL AND coalesce((SELECT sum(amount) FROM public.technician_payments WHERE assignment_id=a.id),0)>=public.assignment_agreed_amount(a.id) THEN 'Paid' ELSE 'Not Paid' END,
      'unit_cost',a.unit_cost,'amount',public.assignment_agreed_amount(a.id)) ORDER BY a.started_at DESC),'[]'::jsonb)
     FROM public.lab_work_order_stage_assignments a WHERE a.lab_organization_id=$1 AND a.work_order_id=p.id
      AND (a.technician_user_id=auth.uid() OR (a.technician_user_id IS NULL AND lower(trim(a.technician_name))=$7))) ELSE '[]'::jsonb END) row,
   p.id,p.%I sort_value
  FROM page p CROSS JOIN LATERAL public.work_order_item_scope($1,p.id,false) scope
 ) SELECT jsonb_build_object(
  'rows',coalesce((SELECT jsonb_agg(row ORDER BY sort_value %s NULLS LAST,id DESC) FROM details),'[]'::jsonb),
  'total',(SELECT count(*) FROM filtered),
  'summary',(SELECT jsonb_build_object('count',count(*),'elements',coalesce(sum(element_count),0),
   'list_price',CASE WHEN $3 OR $6 THEN CASE WHEN count(*)=0 THEN 0 WHEN bool_and(list_price IS NOT NULL) THEN sum(list_price) END END,'final_price',CASE WHEN $3 OR $6 THEN CASE WHEN count(*)=0 THEN 0 WHEN bool_and(final_price IS NOT NULL) THEN sum(final_price) END END,
   'cost_model',CASE WHEN $3 OR $5 THEN CASE WHEN count(*)=0 THEN 0 WHEN NOT bool_or(unknown_model) THEN coalesce(sum(coalesce(own_cost_model,0)),0) END END,
   'cost_modelare',CASE WHEN $3 OR $5 THEN CASE WHEN count(*)=0 THEN 0 WHEN NOT bool_or(unknown_modelare) THEN coalesce(sum(coalesce(own_cost_modelare,0)),0) END END,
   'cost_cer_fin',CASE WHEN $3 OR $5 THEN CASE WHEN count(*)=0 THEN 0 WHEN NOT bool_or(unknown_cer_fin) THEN coalesce(sum(coalesce(own_cost_cer_fin,0)),0) END END,
   'technician_cost',CASE WHEN $5 AND NOT $3 THEN CASE WHEN count(*)=0 THEN 0 WHEN bool_and(own_cost IS NOT NULL) THEN sum(own_cost) END
    WHEN $3 THEN CASE WHEN count(*)=0 THEN 0 WHEN NOT bool_or(unknown_selected) THEN sum(selected_technician_cost) END END,
   'partners',count(DISTINCT nullif(nume_partener,'')),'patients',count(DISTINCT nullif(nume_pacient,''))) FROM filtered),
  'facets',jsonb_build_object(
   'statuses',coalesce((SELECT jsonb_agg(v ORDER BY v) FROM (SELECT DISTINCT status v FROM clinical WHERE coalesce(status,'')<>'') x),'[]'::jsonb),
   'partners',coalesce((SELECT jsonb_agg(v ORDER BY v) FROM (SELECT DISTINCT nume_partener v FROM clinical WHERE coalesce(nume_partener,'')<>'') x),'[]'::jsonb),
   'work_types',coalesce((SELECT jsonb_agg(v ORDER BY v) FROM (SELECT DISTINCT unnest(work_types) v FROM clinical) x),'[]'::jsonb)))
 $query$,predicates,sort_col,sort_dir,sort_col,sort_dir)
 INTO result USING p_lab_organization_id,p_filters,mg,dash,tech,doc,tech_name,rf,rt,df,dt,uf,ut,today,p_limit,p_offset;
 RETURN result;
END;
$function$;
REVOKE ALL ON FUNCTION public.get_work_orders_page(uuid,jsonb,integer,integer) FROM public;
GRANT EXECUTE ON FUNCTION public.get_work_orders_page(uuid,jsonb,integer,integer) TO authenticated;

-- Source: db/schema/20_functions/admin_cleanup.sql
-- Public reads are scoped to the active Flowrise Admin; worker RPCs are service-only.
CREATE OR REPLACE FUNCTION public.cleanup_admin_lab(p_user uuid DEFAULT auth.uid()) RETURNS uuid
LANGUAGE plpgsql STABLE SECURITY DEFINER SET search_path=public AS $$
DECLARE v_lab uuid:=public.get_flowrise_lab_id();
BEGIN
 IF p_user IS NULL OR v_lab IS NULL OR NOT EXISTS(
  SELECT 1 FROM organization_memberships m JOIN profiles p ON p.id=m.user_id
  WHERE m.organization_id=v_lab AND m.user_id=p_user AND lower(m.role)='admin' AND m.status='active' AND p.active
 ) THEN RAISE EXCEPTION 'Access denied'; END IF;
 RETURN v_lab;
END; $$;

CREATE OR REPLACE FUNCTION public.cleanup_size(p_metadata jsonb) RETURNS bigint
LANGUAGE plpgsql IMMUTABLE SET search_path=public AS $$
DECLARE s text:=p_metadata->>'size';
BEGIN
 IF s IS NULL OR s !~ '^\d{1,19}$' THEN RETURN NULL; END IF;
 IF s::numeric>9223372036854775807 THEN RETURN NULL; END IF;
 RETURN s::bigint;
END; $$;

CREATE OR REPLACE FUNCTION public.cleanup_path_matches(p_path text,p_order bigint) RETURNS boolean
LANGUAGE sql IMMUTABLE SET search_path=public AS $$
 SELECT p_path ~ ('^work-orders/'||p_order::text||'/[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}_[^/]+$');
$$;

CREATE OR REPLACE FUNCTION public.cleanup_order_available(p_lab uuid,p_order bigint) RETURNS boolean
LANGUAGE sql STABLE SECURITY DEFINER SET search_path=public AS $$
 SELECT NOT EXISTS(SELECT 1 FROM admin_cleanup_items i JOIN admin_cleanup_jobs j ON j.id=i.job_id
 WHERE j.lab_organization_id=p_lab AND i.order_id=p_order AND i.state='processing');
$$;

CREATE OR REPLACE FUNCTION public.cleanup_internal_item(p_lab uuid,p_order bigint) RETURNS boolean
LANGUAGE sql STABLE SECURITY DEFINER SET search_path=public AS $$
 SELECT coalesce(auth.role()='service_role',false) AND EXISTS(
 SELECT 1 FROM admin_cleanup_items i JOIN admin_cleanup_jobs j ON j.id=i.job_id
 WHERE j.lab_organization_id=p_lab AND i.order_id=p_order AND i.state='processing'
 AND i.id::text=current_setting('flowrise.cleanup_item',true));
$$;

CREATE OR REPLACE FUNCTION public.cleanup_touch_order(p_lab uuid,p_order bigint) RETURNS void
LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$
BEGIN
 IF p_lab IS NULL THEN
  IF (SELECT count(*) FROM lab_work_orders WHERE id=p_order)<>1 THEN RETURN; END IF;
  SELECT lab_organization_id INTO p_lab FROM lab_work_orders WHERE id=p_order;
 END IF;
 PERFORM 1 FROM lab_work_orders WHERE lab_organization_id=p_lab AND id=p_order FOR UPDATE;
 IF NOT public.cleanup_order_available(p_lab,p_order) AND NOT public.cleanup_internal_item(p_lab,p_order) THEN
  RAISE EXCEPTION 'Lucrarea este în curs de curățare.';
 END IF;
 UPDATE lab_work_orders SET cleanup_revision=cleanup_revision+1 WHERE lab_organization_id=p_lab AND id=p_order;
END; $$;

CREATE OR REPLACE FUNCTION public.cleanup_mutation_guard() RETURNS trigger
LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$
DECLARE r jsonb;v_lab uuid;v_order bigint;old_r jsonb;new_r jsonb;target record;
BEGIN
 IF TG_TABLE_NAME='lab_work_orders' THEN
  IF TG_OP='INSERT' THEN
   INSERT INTO lab_work_order_id_watermarks VALUES(NEW.lab_organization_id,NEW.id)
   ON CONFLICT(lab_organization_id) DO UPDATE SET maximum_id=greatest(lab_work_order_id_watermarks.maximum_id,excluded.maximum_id);
   RETURN NEW;
  END IF;
  IF NOT public.cleanup_order_available(OLD.lab_organization_id,OLD.id) AND NOT public.cleanup_internal_item(OLD.lab_organization_id,OLD.id) THEN
   RAISE EXCEPTION 'Lucrarea este în curs de curățare.';
  END IF;
  IF TG_OP='UPDATE' THEN
   IF NEW.lab_organization_id IS DISTINCT FROM OLD.lab_organization_id OR NEW.id IS DISTINCT FROM OLD.id THEN RAISE EXCEPTION 'Work Order identity is immutable'; END IF;
   NEW.cleanup_revision:=greatest(NEW.cleanup_revision,OLD.cleanup_revision+1);RETURN NEW;
  END IF;
  RETURN OLD;
 END IF;
 IF TG_OP<>'INSERT' THEN old_r:=to_jsonb(OLD);END IF;
 IF TG_OP<>'DELETE' THEN new_r:=to_jsonb(NEW);END IF;
 -- Resolve both parents before locking, so a moved child invalidates both selections.
 FOR target IN
  SELECT DISTINCT x.lab,x.ord FROM (
   SELECT CASE WHEN v ? 'assignment_id' THEN a.lab_organization_id ELSE nullif(v->>'lab_organization_id','')::uuid END lab,
          CASE WHEN v ? 'assignment_id' THEN a.work_order_id ELSE coalesce(v->>'work_order_id',v->>'legacy_work_order_id')::bigint END ord
   FROM (SELECT old_r v UNION ALL SELECT new_r) vals
   LEFT JOIN lab_work_order_stage_assignments a ON a.id=nullif(v->>'assignment_id','')::uuid
   WHERE v IS NOT NULL
  ) x WHERE x.ord IS NOT NULL ORDER BY x.lab NULLS LAST,x.ord
 LOOP PERFORM public.cleanup_touch_order(target.lab,target.ord);END LOOP;
 IF TG_OP='DELETE' THEN RETURN OLD;END IF;RETURN NEW;
END; $$;

CREATE OR REPLACE FUNCTION public.admin_storage_usage() RETURNS jsonb
LANGUAGE plpgsql STABLE SECURITY DEFINER SET search_path=public AS $$
DECLARE result jsonb;
BEGIN
 PERFORM public.cleanup_admin_lab();
 SELECT jsonb_build_object('used_bytes',coalesce(sum(bytes),0)::text,'unknown_size_count',coalesce(sum(unknowns),0),
 'measured_at',now(),'buckets',coalesce(jsonb_agg(jsonb_build_object('name',bucket_id,'used_bytes',bytes::text,'unknown_size_count',unknowns) ORDER BY bucket_id),'[]'))
 INTO result FROM (SELECT bucket_id,coalesce(sum(public.cleanup_size(metadata)),0) bytes,count(*) FILTER(WHERE public.cleanup_size(metadata) IS NULL) unknowns FROM storage.objects GROUP BY bucket_id) b;
 RETURN result;
END; $$;

CREATE OR REPLACE FUNCTION public.cleanup_job_json(p_job uuid) RETURNS jsonb
LANGUAGE sql STABLE SECURITY DEFINER SET search_path=public AS $$
 SELECT jsonb_build_object('id',j.id,'action',j.action,'state',j.state,'from',j.date_from,'to',j.date_to,'expires_at',j.expires_at,
 'reconcile_after',j.reconcile_after,'missing_dates_count',j.missing_dates_count,
 'bytes',(SELECT coalesce(sum(i.bytes),0)::text FROM admin_cleanup_items i WHERE i.job_id=j.id),
 'counts',coalesce((SELECT jsonb_object_agg(key,total) FROM (SELECT c.key,sum(c.value::numeric) total FROM admin_cleanup_items i CROSS JOIN LATERAL jsonb_each_text(i.counts) c WHERE i.job_id=j.id GROUP BY c.key) s),'{}'),
 'progress',(SELECT jsonb_build_object('total',count(*),'completed',count(*) FILTER(WHERE state='completed'),'skipped',count(*) FILTER(WHERE state='skipped'),'failed',count(*) FILTER(WHERE state='failed')) FROM admin_cleanup_items WHERE job_id=j.id),
 'errors',coalesce((SELECT jsonb_agg(jsonb_build_object('order_id',order_id::text,'code',error_code,'message',error_message)) FROM admin_cleanup_items WHERE job_id=j.id AND error_code IS NOT NULL),'[]'))
 FROM admin_cleanup_jobs j WHERE j.id=p_job;
$$;

CREATE OR REPLACE FUNCTION public.cleanup_owned_job(p_job uuid) RETURNS void
LANGUAGE plpgsql STABLE SECURITY DEFINER SET search_path=public AS $$
DECLARE v_lab uuid:=public.cleanup_admin_lab();
BEGIN
 IF NOT EXISTS(SELECT 1 FROM admin_cleanup_jobs WHERE id=p_job AND lab_organization_id=v_lab AND created_by=auth.uid()) THEN RAISE EXCEPTION 'Access denied';END IF;
END; $$;

CREATE OR REPLACE FUNCTION public.admin_cleanup_status(p_job_id uuid,p_limit integer DEFAULT 50,p_offset integer DEFAULT 0) RETURNS jsonb
LANGUAGE plpgsql STABLE SECURITY DEFINER SET search_path=public AS $$
DECLARE result jsonb;
BEGIN
 PERFORM public.cleanup_owned_job(p_job_id);
 IF p_limit IS NULL OR p_limit<1 OR p_limit>200 OR p_offset IS NULL OR p_offset<0 THEN RAISE EXCEPTION 'Invalid pagination';END IF;
 SELECT jsonb_build_object('job',public.cleanup_job_json(p_job_id),'offset',p_offset,'limit',p_limit,
 'total',(SELECT count(*) FROM admin_cleanup_items WHERE job_id=p_job_id),
 'orders',coalesce(jsonb_agg(jsonb_build_object('order_id',i.order_id::text,'state',i.state,'counts',i.counts,'bytes',i.bytes::text) ORDER BY i.order_id),'[]'))
 INTO result FROM (SELECT * FROM admin_cleanup_items WHERE job_id=p_job_id ORDER BY order_id LIMIT p_limit OFFSET p_offset) i;
 RETURN result;
END; $$;

CREATE OR REPLACE FUNCTION public.admin_cleanup_jobs(p_limit integer DEFAULT 20) RETURNS jsonb
LANGUAGE plpgsql STABLE SECURITY DEFINER SET search_path=public AS $$
DECLARE v_lab uuid:=public.cleanup_admin_lab();result jsonb;
BEGIN
 IF p_limit IS NULL OR p_limit<1 OR p_limit>100 THEN RAISE EXCEPTION 'Invalid pagination';END IF;
 SELECT coalesce(jsonb_agg(public.cleanup_job_json(id) ORDER BY created_at DESC),'[]') INTO result FROM
 (SELECT id,created_at FROM admin_cleanup_jobs WHERE lab_organization_id=v_lab AND created_by=auth.uid() ORDER BY created_at DESC LIMIT p_limit) j;
 RETURN result;
END; $$;

CREATE OR REPLACE FUNCTION public.admin_cleanup_preview(p_action text,p_from date,p_to date) RETURNS jsonb
LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$
DECLARE v_lab uuid:=public.cleanup_admin_lab();v_job uuid;v_item uuid;o record;v_ambiguous boolean;v_counts jsonb;v_bytes bigint;
BEGIN
 IF p_action IS NULL OR p_action NOT IN ('files','clinical','all') OR p_from IS NULL OR p_to IS NULL OR p_from>p_to THEN RAISE EXCEPTION 'Invalid action or date range';END IF;
 INSERT INTO admin_cleanup_jobs(lab_organization_id,created_by,action,date_from,date_to,missing_dates_count)
 VALUES(v_lab,auth.uid(),p_action,p_from,p_to,(SELECT count(*) FROM lab_work_orders WHERE lab_organization_id=v_lab AND coalesce(data_receptie,created_at) IS NULL)) RETURNING id INTO v_job;
 FOR o IN SELECT * FROM lab_work_orders WHERE lab_organization_id=v_lab
 AND coalesce(data_receptie,created_at)>=(p_from::timestamp AT TIME ZONE 'Europe/Bucharest')
 AND coalesce(data_receptie,created_at)<((p_to+1)::timestamp AT TIME ZONE 'Europe/Bucharest') ORDER BY id FOR SHARE
 LOOP
  v_ambiguous:=p_action<>'clinical' AND (
   EXISTS(SELECT 1 FROM work_order_files f WHERE f.legacy_work_order_id=o.id AND
    (f.lab_organization_id=v_lab OR f.lab_organization_id IS NULL) AND
    (f.bucket_name<>'work-order-files' OR NOT public.cleanup_path_matches(f.object_path,o.id) OR
     (f.lab_organization_id IS NULL AND (SELECT count(*) FROM lab_work_orders WHERE id=o.id)<>1))) OR
   EXISTS(SELECT 1 FROM storage.objects s WHERE s.bucket_id='work-order-files' AND public.cleanup_path_matches(s.name,o.id) AND
    (EXISTS(SELECT 1 FROM work_order_files f WHERE f.object_path=s.name AND (f.legacy_work_order_id<>o.id OR (f.lab_organization_id IS NOT NULL AND f.lab_organization_id<>v_lab))) OR
     (NOT EXISTS(SELECT 1 FROM work_order_files f WHERE f.object_path=s.name AND f.lab_organization_id=v_lab) AND (SELECT count(*) FROM lab_work_orders WHERE id=o.id)<>1)))
  );
  INSERT INTO admin_cleanup_items(job_id,order_id,revision,state,error_code,error_message)
  VALUES(v_job,o.id,o.cleanup_revision,CASE WHEN v_ambiguous THEN 'skipped' ELSE 'pending' END,
   CASE WHEN v_ambiguous THEN 'ambiguous_files' END,CASE WHEN v_ambiguous THEN 'Asocierea fișierelor este ambiguă sau traseul nu este valid.' END) RETURNING id INTO v_item;
  IF p_action<>'clinical' AND NOT v_ambiguous THEN
   INSERT INTO admin_cleanup_files(item_id,bucket,object_path,metadata_id,size_bytes,object_version)
   SELECT v_item,'work-order-files',paths.path,f.id,public.cleanup_size(s.metadata),CASE WHEN s.name IS NOT NULL THEN md5(coalesce(s.metadata::text,'null')) END
   FROM (
    SELECT object_path path FROM work_order_files WHERE legacy_work_order_id=o.id AND (lab_organization_id=v_lab OR lab_organization_id IS NULL) AND bucket_name='work-order-files'
    UNION SELECT name FROM storage.objects WHERE bucket_id='work-order-files' AND public.cleanup_path_matches(name,o.id)
   ) paths LEFT JOIN work_order_files f ON f.object_path=paths.path LEFT JOIN storage.objects s ON s.bucket_id='work-order-files' AND s.name=paths.path;
  END IF;
  SELECT jsonb_build_object(
   'files',(SELECT count(*) FROM admin_cleanup_files WHERE item_id=v_item),
   'unknown_file_sizes',(SELECT count(*) FROM admin_cleanup_files WHERE item_id=v_item AND size_bytes IS NULL),
   'clinical_cases',(SELECT count(*) FROM lab_patient_cases WHERE lab_organization_id=v_lab AND work_order_id=o.id),
   'items',(SELECT count(*) FROM lab_work_order_items WHERE lab_organization_id=v_lab AND work_order_id=o.id),
   'price_lines',(SELECT count(*) FROM lab_work_order_price_lines WHERE lab_organization_id=v_lab AND work_order_id=o.id),
   'assignments',(SELECT count(*) FROM lab_work_order_stage_assignments WHERE lab_organization_id=v_lab AND work_order_id=o.id),
   'payments',(SELECT count(*) FROM technician_payments p JOIN lab_work_order_stage_assignments a ON a.id=p.assignment_id WHERE a.lab_organization_id=v_lab AND a.work_order_id=o.id),
   'cost_lines',(SELECT count(*) FROM lab_work_order_assignment_cost_lines c JOIN lab_work_order_stage_assignments a ON a.id=c.assignment_id WHERE a.lab_organization_id=v_lab AND a.work_order_id=o.id),
   'adjustments',(SELECT count(*) FROM lab_work_order_assignment_adjustments c JOIN lab_work_order_stage_assignments a ON a.id=c.assignment_id WHERE a.lab_organization_id=v_lab AND a.work_order_id=o.id),
   'financial_audit',(SELECT count(*) FROM work_order_financial_audit WHERE lab_organization_id=v_lab AND work_order_id=o.id)) INTO v_counts;
  UPDATE admin_cleanup_items SET counts=v_counts,bytes=(SELECT coalesce(sum(size_bytes),0) FROM admin_cleanup_files WHERE item_id=v_item) WHERE id=v_item;
 END LOOP;
 RETURN public.cleanup_job_json(v_job);
END; $$;

CREATE OR REPLACE FUNCTION public.cleanup_require_service() RETURNS void
LANGUAGE plpgsql STABLE SET search_path=public AS $$
BEGIN IF auth.role() IS DISTINCT FROM 'service_role' THEN RAISE EXCEPTION 'Access denied';END IF;END; $$;

CREATE OR REPLACE FUNCTION public.cleanup_refresh_job(p_job uuid) RETURNS jsonb
LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$
DECLARE v_state text;
BEGIN
 SELECT CASE WHEN count(*) FILTER(WHERE state IN ('pending','processing'))>0 THEN 'running'
 WHEN count(*) FILTER(WHERE state='awaiting_uploads')>0 THEN 'awaiting_uploads'
 WHEN count(*) FILTER(WHERE state IN ('skipped','failed'))>0 THEN CASE WHEN count(*) FILTER(WHERE state IN ('completed','skipped'))=0 THEN 'failed' ELSE 'partial' END
 ELSE 'completed' END INTO v_state FROM admin_cleanup_items WHERE job_id=p_job;
 UPDATE admin_cleanup_jobs SET state=v_state,updated_at=now() WHERE id=p_job;
 RETURN public.cleanup_job_json(p_job);
END; $$;

CREATE OR REPLACE FUNCTION public.admin_cleanup_confirm(p_job_id uuid,p_confirmation text DEFAULT '') RETURNS jsonb
LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$
DECLARE j admin_cleanup_jobs%rowtype;
BEGIN
 PERFORM public.cleanup_owned_job(p_job_id);
 SELECT * INTO j FROM admin_cleanup_jobs WHERE id=p_job_id FOR UPDATE;
 IF j.action='all' AND p_confirmation IS DISTINCT FROM 'ȘTERGE' THEN RAISE EXCEPTION 'Invalid confirmation';END IF;
 IF j.state<>'preview' THEN RETURN public.cleanup_job_json(j.id);END IF;
 IF now()>=j.expires_at THEN RAISE EXCEPTION 'Preview expired';END IF;
 UPDATE admin_cleanup_jobs SET state='running',confirmed_at=now(),reconcile_after=CASE WHEN action<>'clinical' THEN now()+interval '2 hours 5 minutes' END WHERE id=j.id;
 RETURN public.cleanup_refresh_job(j.id);
END; $$;

CREATE OR REPLACE FUNCTION public.cleanup_lease(p_job uuid,p_order bigint,p_worker uuid) RETURNS uuid
LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$
DECLARE i admin_cleanup_items%rowtype;j admin_cleanup_jobs%rowtype;
BEGIN
 PERFORM public.cleanup_require_service();
 SELECT * INTO j FROM admin_cleanup_jobs WHERE id=p_job;
 IF NOT FOUND THEN RAISE EXCEPTION 'Job not found';END IF;
 PERFORM public.cleanup_admin_lab(j.created_by);
 SELECT * INTO i FROM admin_cleanup_items WHERE job_id=p_job AND order_id=p_order FOR UPDATE;
 IF NOT FOUND OR i.state<>'processing' OR i.worker_id IS DISTINCT FROM p_worker OR i.lease_until<=now() THEN RAISE EXCEPTION 'Invalid worker lease';END IF;
 RETURN i.id;
END; $$;

CREATE OR REPLACE FUNCTION public.admin_cleanup_claim(p_job_id uuid,p_worker_id uuid) RETURNS jsonb
LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$
DECLARE j admin_cleanup_jobs%rowtype;i admin_cleanup_items%rowtype;v_rev bigint;
BEGIN
 PERFORM public.cleanup_require_service();
 IF p_worker_id IS NULL THEN RAISE EXCEPTION 'Invalid worker';END IF;
 SELECT * INTO j FROM admin_cleanup_jobs WHERE id=p_job_id FOR UPDATE;
 IF NOT FOUND OR j.confirmed_at IS NULL THEN RAISE EXCEPTION 'Job not confirmed';END IF;
 PERFORM public.cleanup_admin_lab(j.created_by);
 FOR i IN SELECT * FROM admin_cleanup_items WHERE job_id=j.id AND
 (state IN ('pending','failed') OR (state='processing' AND lease_until<now()) OR (state='awaiting_uploads' AND j.reconcile_after<=now())) ORDER BY CASE WHEN state='failed' THEN 1 ELSE 0 END,order_id FOR UPDATE SKIP LOCKED
 LOOP
  IF NOT i.initial_finished THEN
   SELECT cleanup_revision INTO v_rev FROM lab_work_orders WHERE lab_organization_id=j.lab_organization_id AND id=i.order_id FOR UPDATE;
   IF NOT FOUND OR v_rev<>i.revision THEN
    UPDATE admin_cleanup_items SET state='skipped',error_code='stale_order',error_message='Lucrarea s-a modificat după previzualizare.' WHERE id=i.id;CONTINUE;
   END IF;
   IF j.action<>'clinical' AND (
    EXISTS(SELECT 1 FROM admin_cleanup_files f LEFT JOIN storage.objects s ON s.bucket_id=f.bucket AND s.name=f.object_path
     WHERE f.item_id=i.id AND NOT f.initial_done AND f.object_version IS DISTINCT FROM CASE WHEN s.name IS NOT NULL THEN md5(coalesce(s.metadata::text,'null')) END
     AND NOT (s.name IS NULL AND i.state IN ('failed','processing'))) OR
    EXISTS(SELECT 1 FROM storage.objects s WHERE s.bucket_id='work-order-files' AND public.cleanup_path_matches(s.name,i.order_id) AND
     NOT EXISTS(SELECT 1 FROM admin_cleanup_files f WHERE f.item_id=i.id AND f.object_path=s.name))
   ) THEN
    UPDATE admin_cleanup_items SET state='skipped',error_code='stale_files',error_message='Fișierele s-au modificat după previzualizare.' WHERE id=i.id;CONTINUE;
   END IF;
   IF j.action='all' AND EXISTS(
    SELECT 1 FROM technician_payments p JOIN technician_payments orig ON orig.id=p.reversal_of
    JOIN lab_work_order_stage_assignments a ON a.id=p.assignment_id JOIN lab_work_order_stage_assignments b ON b.id=orig.assignment_id
    WHERE ((a.lab_organization_id=j.lab_organization_id AND a.work_order_id=i.order_id)<>(b.lab_organization_id=j.lab_organization_id AND b.work_order_id=i.order_id))
   ) THEN
    UPDATE admin_cleanup_items SET state='skipped',error_code='external_reversal',error_message='O reversare este legată de altă lucrare.' WHERE id=i.id;CONTINUE;
   END IF;
  END IF;
  -- An item already processing elsewhere must never permit a second job on the same order.
  IF EXISTS(SELECT 1 FROM admin_cleanup_items x JOIN admin_cleanup_jobs y ON y.id=x.job_id WHERE x.id<>i.id AND x.order_id=i.order_id AND y.lab_organization_id=j.lab_organization_id AND x.state='processing') THEN CONTINUE;END IF;
  UPDATE admin_cleanup_items SET state='processing',worker_id=p_worker_id,lease_until=now()+interval '120 seconds',error_code=NULL,error_message=NULL WHERE id=i.id;
  RETURN jsonb_build_object('order_id',i.order_id::text,'action',j.action,'reconciliation',i.initial_finished,'file_count',(SELECT count(*) FROM admin_cleanup_files WHERE item_id=i.id));
 END LOOP;
 PERFORM public.cleanup_refresh_job(j.id);RETURN NULL;
END; $$;

CREATE OR REPLACE FUNCTION public.admin_cleanup_files(p_job_id uuid,p_order_id bigint,p_worker_id uuid,p_offset integer DEFAULT 0,p_limit integer DEFAULT 100) RETURNS jsonb
LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$
DECLARE v_item uuid;result jsonb;
BEGIN
 v_item:=public.cleanup_lease(p_job_id,p_order_id,p_worker_id);
 IF p_offset IS NULL OR p_offset<0 OR p_limit IS NULL OR p_limit<1 OR p_limit>100 THEN RAISE EXCEPTION 'Invalid pagination';END IF;
 SELECT jsonb_build_object('files',coalesce(jsonb_agg(jsonb_build_object('path',object_path,'bucket',bucket,'initial_done',initial_done,'reconciled',reconciled) ORDER BY id),'[]'),
 'total',(SELECT count(*) FROM admin_cleanup_files WHERE item_id=v_item)) INTO result FROM
 (SELECT * FROM admin_cleanup_files WHERE item_id=v_item ORDER BY id OFFSET p_offset LIMIT p_limit) f;
 RETURN result;
END; $$;

CREATE OR REPLACE FUNCTION public.admin_cleanup_checkpoint(p_job_id uuid,p_order_id bigint,p_worker_id uuid,p_paths text[],p_reconciliation boolean DEFAULT false) RETURNS jsonb
LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$
DECLARE v_item uuid;v_initial boolean;
BEGIN
 v_item:=public.cleanup_lease(p_job_id,p_order_id,p_worker_id);
 SELECT initial_finished INTO v_initial FROM admin_cleanup_items WHERE id=v_item;
 IF p_reconciliation IS DISTINCT FROM v_initial OR p_paths IS NULL OR cardinality(p_paths)>100 OR
 EXISTS(SELECT 1 FROM unnest(p_paths) path WHERE NOT EXISTS(SELECT 1 FROM admin_cleanup_files WHERE item_id=v_item AND object_path=path)) THEN RAISE EXCEPTION 'Invalid checkpoint';END IF;
 UPDATE admin_cleanup_files SET initial_done=CASE WHEN NOT p_reconciliation THEN true ELSE initial_done END,reconciled=CASE WHEN p_reconciliation THEN true ELSE reconciled END WHERE item_id=v_item AND object_path=ANY(p_paths);
 UPDATE admin_cleanup_items SET lease_until=now()+interval '120 seconds' WHERE id=v_item;
 RETURN public.cleanup_job_json(p_job_id);
END; $$;

CREATE OR REPLACE FUNCTION public.admin_cleanup_finish(p_job_id uuid,p_order_id bigint,p_worker_id uuid,p_storage_success boolean,p_error_code text DEFAULT NULL) RETURNS jsonb
LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$
DECLARE v_item uuid;j admin_cleanup_jobs%rowtype;v_assignments uuid[];v_state text;
BEGIN
 v_item:=public.cleanup_lease(p_job_id,p_order_id,p_worker_id);
 SELECT * INTO j FROM admin_cleanup_jobs WHERE id=p_job_id;
 IF (SELECT initial_finished FROM admin_cleanup_items WHERE id=v_item) THEN RAISE EXCEPTION 'Use reconciliation finish';END IF;
 IF NOT coalesce(p_storage_success,false) THEN
  UPDATE admin_cleanup_items SET state='failed',worker_id=NULL,lease_until=NULL,error_code=CASE WHEN p_error_code='database_failed' THEN 'database_failed' ELSE 'storage_failed' END,error_message=CASE WHEN p_error_code='database_failed' THEN 'Ștergerea datelor a eșuat. Operația poate fi reluată.' ELSE 'Fișierele nu au fost eliminate complet. Operația poate fi reluată.' END WHERE id=v_item;
  RETURN public.cleanup_refresh_job(j.id);
 END IF;
 IF EXISTS(SELECT 1 FROM admin_cleanup_files WHERE item_id=v_item AND NOT initial_done) THEN RAISE EXCEPTION 'Storage checkpoint incomplete';END IF;
 PERFORM set_config('flowrise.cleanup_item',v_item::text,true);
 IF j.action IN ('files','all') THEN
  DELETE FROM work_order_files f USING admin_cleanup_files m WHERE m.item_id=v_item AND f.id=m.metadata_id;
 END IF;
 IF j.action IN ('clinical','all') THEN
  DELETE FROM lab_patient_cases WHERE lab_organization_id=j.lab_organization_id AND work_order_id=p_order_id;
 END IF;
 IF j.action='clinical' THEN
  UPDATE lab_work_orders SET nume_pacient=NULL,clinical_cleared_at=now(),clinical_cleanup_generation=clinical_cleanup_generation+1,updated_at=now() WHERE lab_organization_id=j.lab_organization_id AND id=p_order_id;
 END IF;
 IF j.action='all' THEN
  SELECT coalesce(array_agg(id),'{}') INTO v_assignments FROM lab_work_order_stage_assignments WHERE lab_organization_id=j.lab_organization_id AND work_order_id=p_order_id;
  DELETE FROM technician_payments WHERE assignment_id=ANY(v_assignments);
  DELETE FROM lab_work_order_assignment_adjustments WHERE assignment_id=ANY(v_assignments);
  DELETE FROM lab_work_order_assignment_cost_lines WHERE assignment_id=ANY(v_assignments);
  DELETE FROM lab_work_order_stage_assignments WHERE id=ANY(v_assignments);
  DELETE FROM lab_work_order_items WHERE lab_organization_id=j.lab_organization_id AND work_order_id=p_order_id;
  DELETE FROM lab_work_order_price_lines WHERE lab_organization_id=j.lab_organization_id AND work_order_id=p_order_id;
  DELETE FROM work_order_financial_audit WHERE lab_organization_id=j.lab_organization_id AND work_order_id=p_order_id;
  DELETE FROM lab_work_orders WHERE lab_organization_id=j.lab_organization_id AND id=p_order_id;
 END IF;
 v_state:=CASE WHEN j.action<>'clinical' AND EXISTS(SELECT 1 FROM admin_cleanup_files WHERE item_id=v_item) THEN 'awaiting_uploads' ELSE 'completed' END;
 UPDATE admin_cleanup_items SET state=v_state,initial_finished=true,worker_id=NULL,lease_until=NULL WHERE id=v_item;
 RETURN public.cleanup_refresh_job(j.id);
END; $$;

CREATE OR REPLACE FUNCTION public.admin_cleanup_reconcile_finish(p_job_id uuid,p_order_id bigint,p_worker_id uuid,p_storage_success boolean) RETURNS jsonb
LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$
DECLARE v_item uuid;j admin_cleanup_jobs%rowtype;
BEGIN
 v_item:=public.cleanup_lease(p_job_id,p_order_id,p_worker_id);SELECT * INTO j FROM admin_cleanup_jobs WHERE id=p_job_id;
 IF NOT (SELECT initial_finished FROM admin_cleanup_items WHERE id=v_item) OR j.reconcile_after IS NULL OR now()<j.reconcile_after THEN RAISE EXCEPTION 'Reconciliation not due';END IF;
 IF coalesce(p_storage_success,false) AND EXISTS(SELECT 1 FROM admin_cleanup_files WHERE item_id=v_item AND NOT reconciled) THEN RAISE EXCEPTION 'Reconciliation checkpoint incomplete';END IF;
 UPDATE admin_cleanup_items SET state=CASE WHEN coalesce(p_storage_success,false) THEN 'completed' ELSE 'failed' END,worker_id=NULL,lease_until=NULL,
 error_code=CASE WHEN NOT coalesce(p_storage_success,false) THEN 'reconciliation_failed' END,
 error_message=CASE WHEN NOT coalesce(p_storage_success,false) THEN 'Verificarea încărcărilor întârziate a eșuat.' END WHERE id=v_item;
 RETURN public.cleanup_refresh_job(j.id);
END; $$;

CREATE OR REPLACE FUNCTION public.admin_cleanup_due(p_limit integer DEFAULT 10) RETURNS jsonb
LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$
DECLARE result jsonb;
BEGIN
 PERFORM public.cleanup_require_service();
 IF p_limit IS NULL OR p_limit<1 OR p_limit>10 THEN RAISE EXCEPTION 'Invalid limit';END IF;
 SELECT coalesce(jsonb_agg(id),'[]') INTO result FROM (SELECT j.id FROM admin_cleanup_jobs j WHERE j.confirmed_at IS NOT NULL AND
 EXISTS(SELECT 1 FROM admin_cleanup_items i WHERE i.job_id=j.id AND (i.state IN ('pending','failed') OR (i.state='processing' AND i.lease_until<now()) OR (i.state='awaiting_uploads' AND j.reconcile_after<=now())))
 AND EXISTS(SELECT 1 FROM organization_memberships m JOIN profiles p ON p.id=m.user_id WHERE m.organization_id=j.lab_organization_id AND m.user_id=j.created_by AND m.status='active' AND lower(m.role)='admin' AND p.active)
 ORDER BY j.updated_at LIMIT p_limit) j;
 RETURN result;
END; $$;


CREATE OR REPLACE FUNCTION public.get_work_order_cleanup_state(p_lab_organization_id uuid,p_work_order_id bigint) RETURNS jsonb
LANGUAGE plpgsql STABLE SECURITY DEFINER SET search_path=public AS $$
DECLARE result jsonb;
BEGIN
 IF auth.uid() IS NULL OR NOT coalesce(public.can_access_work_order(p_lab_organization_id,p_work_order_id),false) OR
 NOT (public.has_org_role(p_lab_organization_id,ARRAY['Admin','Manager','Technician']) OR public.is_connected_doctor_for_lab(p_lab_organization_id)) THEN RAISE EXCEPTION 'Access denied';END IF;
 SELECT jsonb_build_object('cleanup_revision',cleanup_revision::text,'clinical_cleanup_generation',clinical_cleanup_generation::text,'clinical_cleared_at',clinical_cleared_at)
 INTO result FROM lab_work_orders WHERE lab_organization_id=p_lab_organization_id AND id=p_work_order_id;
 IF result IS NULL THEN RAISE EXCEPTION 'Work Order not found';END IF;
 RETURN result;
END; $$;
REVOKE ALL ON FUNCTION public.get_work_order_cleanup_state(uuid,bigint) FROM PUBLIC,anon;
GRANT EXECUTE ON FUNCTION public.get_work_order_cleanup_state(uuid,bigint) TO authenticated;

CREATE OR REPLACE FUNCTION public.admin_cleanup_worker_status(p_job_id uuid) RETURNS jsonb
LANGUAGE plpgsql STABLE SECURITY DEFINER SET search_path=public AS $$
DECLARE v_owner uuid;
BEGIN
 PERFORM public.cleanup_require_service();SELECT created_by INTO v_owner FROM admin_cleanup_jobs WHERE id=p_job_id;
 IF v_owner IS NULL THEN RAISE EXCEPTION 'Job not found';END IF;PERFORM public.cleanup_admin_lab(v_owner);RETURN public.cleanup_job_json(p_job_id);
END; $$;
CREATE OR REPLACE FUNCTION public.admin_cleanup_yield(p_job_id uuid,p_order_id bigint,p_worker_id uuid) RETURNS jsonb
LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$
DECLARE v_item uuid;
BEGIN
 v_item:=public.cleanup_lease(p_job_id,p_order_id,p_worker_id);
 UPDATE admin_cleanup_items SET state=CASE WHEN initial_finished THEN 'awaiting_uploads' ELSE 'pending' END,worker_id=NULL,lease_until=NULL WHERE id=v_item;
 RETURN public.cleanup_refresh_job(p_job_id);
END; $$;

-- Source: db/schema/30_policies/33_admin_cleanup.sql
-- All reads/mutations use checked RPCs; tables have no browser policies.
REVOKE ALL ON public.admin_cleanup_jobs,public.admin_cleanup_items,public.admin_cleanup_files,public.lab_work_order_id_watermarks FROM PUBLIC,anon,authenticated;
DO $$ DECLARE t text;BEGIN
 FOREACH t IN ARRAY ARRAY['lab_work_orders','lab_patient_cases','work_order_files','lab_work_order_items','lab_work_order_price_lines','lab_work_order_stage_assignments','lab_work_order_assignment_cost_lines','lab_work_order_assignment_adjustments','technician_payments','work_order_financial_audit'] LOOP
  EXECUTE format('DROP TRIGGER IF EXISTS cleanup_mutation_guard ON public.%I',t);
  EXECUTE format('CREATE TRIGGER cleanup_mutation_guard BEFORE INSERT OR UPDATE OR DELETE ON public.%I FOR EACH ROW EXECUTE FUNCTION public.cleanup_mutation_guard()',t);
 END LOOP;
END; $$;
DO $$ DECLARE f record;BEGIN
 FOR f IN SELECT p.oid::regprocedure signature FROM pg_proc p JOIN pg_namespace n ON n.oid=p.pronamespace WHERE n.nspname='public' AND (p.proname LIKE 'cleanup_%' OR p.proname LIKE 'admin_cleanup_%' OR p.proname='admin_storage_usage') LOOP
  EXECUTE format('REVOKE ALL ON FUNCTION %s FROM PUBLIC,anon,authenticated',f.signature);
 END LOOP;
END; $$;
GRANT EXECUTE ON FUNCTION public.admin_storage_usage(),public.admin_cleanup_preview(text,date,date),public.admin_cleanup_status(uuid,integer,integer),public.admin_cleanup_jobs(integer) TO authenticated;
GRANT EXECUTE ON FUNCTION public.admin_cleanup_confirm(uuid,text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.admin_cleanup_claim(uuid,uuid),public.admin_cleanup_files(uuid,bigint,uuid,integer,integer),public.admin_cleanup_checkpoint(uuid,bigint,uuid,text[],boolean),public.admin_cleanup_finish(uuid,bigint,uuid,boolean,text),public.admin_cleanup_due(integer),public.admin_cleanup_reconcile_finish(uuid,bigint,uuid,boolean) TO service_role;
GRANT EXECUTE ON FUNCTION public.admin_cleanup_worker_status(uuid),public.admin_cleanup_yield(uuid,bigint,uuid),public.cleanup_order_available(uuid,bigint) TO service_role;

NOTIFY pgrst, 'reload schema';
COMMIT;
