-- Lab Partner commercial orders, approval, processing and urgency pricing.
CREATE TABLE IF NOT EXISTS public.lab_partner_user_links (
  lab_organization_id uuid NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE,
  user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  partner_id uuid NOT NULL REFERENCES public.lab_partners(id) ON DELETE RESTRICT,
  created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (lab_organization_id,user_id)
);
CREATE OR REPLACE FUNCTION public.validate_lab_partner_link()
RETURNS trigger LANGUAGE plpgsql SET search_path=public AS $$
BEGIN
 IF NOT EXISTS(SELECT 1 FROM public.lab_partners p WHERE p.id=NEW.partner_id
  AND p.lab_organization_id=NEW.lab_organization_id AND p.active) THEN
  RAISE EXCEPTION 'Lab Partner mapping requires an active partner in this laboratory';
 END IF;
 RETURN NEW;
END $$;
DROP TRIGGER IF EXISTS validate_lab_partner_link ON public.lab_partner_user_links;
CREATE TRIGGER validate_lab_partner_link BEFORE INSERT OR UPDATE ON public.lab_partner_user_links
FOR EACH ROW EXECUTE FUNCTION public.validate_lab_partner_link();
CREATE TABLE IF NOT EXISTS public.lab_order_pricing_settings (
  lab_organization_id uuid PRIMARY KEY REFERENCES public.organizations(id) ON DELETE CASCADE,
  default_contract text NOT NULL DEFAULT 'General', urgent_window_hours integer NOT NULL DEFAULT 24 CHECK (urgent_window_hours >= 0),
  timezone text NOT NULL DEFAULT 'Europe/Bucharest' CHECK (timezone='Europe/Bucharest'), updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE TABLE IF NOT EXISTS public.lab_contract_pricing_defaults (
  lab_organization_id uuid NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE, contract text NOT NULL,
  urgent_percent numeric(7,2) NOT NULL DEFAULT 0 CHECK (urgent_percent >= 0), processing_amount numeric(14,2) NOT NULL DEFAULT 0 CHECK (processing_amount >= 0),
  PRIMARY KEY (lab_organization_id,contract)
);
ALTER TABLE public.lab_work_types ADD COLUMN IF NOT EXISTS processing_enabled boolean NOT NULL DEFAULT false;
ALTER TABLE public.lab_contract_work_prices ADD COLUMN IF NOT EXISTS urgent_percent_override numeric(7,2) CHECK (urgent_percent_override IS NULL OR urgent_percent_override >= 0), ADD COLUMN IF NOT EXISTS processing_amount_override numeric(14,2) CHECK (processing_amount_override IS NULL OR processing_amount_override >= 0);
ALTER TABLE public.lab_work_orders ADD COLUMN IF NOT EXISTS order_origin text NOT NULL DEFAULT 'internal' CHECK (order_origin IN ('doctor','lab_partner','internal')), ADD COLUMN IF NOT EXISTS partner_id uuid REFERENCES public.lab_partners(id), ADD COLUMN IF NOT EXISTS deadline_at timestamptz, ADD COLUMN IF NOT EXISTS approval_state text NOT NULL DEFAULT 'approved' CHECK (approval_state IN ('approved','pending','rejected')), ADD COLUMN IF NOT EXISTS approval_reviewed_at timestamptz, ADD COLUMN IF NOT EXISTS approval_reviewed_by_user_id uuid REFERENCES auth.users(id), ADD COLUMN IF NOT EXISTS approval_reason text;
UPDATE public.lab_work_orders SET order_origin='internal',approval_state='approved' WHERE order_origin IS NULL OR approval_state IS NULL;
CREATE TABLE IF NOT EXISTS public.lab_partner_work_order_items (
  lab_organization_id uuid NOT NULL, work_order_id bigint NOT NULL, line_no integer NOT NULL CHECK(line_no>0), work_type text NOT NULL, color text, quantity integer NOT NULL CHECK(quantity>0), processing_requested boolean NOT NULL DEFAULT false, note text,
  PRIMARY KEY(lab_organization_id,work_order_id,line_no), FOREIGN KEY(lab_organization_id,work_order_id) REFERENCES public.lab_work_orders(lab_organization_id,id) ON DELETE CASCADE
);
CREATE TABLE IF NOT EXISTS public.lab_partner_work_order_price_lines (
  lab_organization_id uuid NOT NULL, work_order_id bigint NOT NULL, line_no integer NOT NULL, contract text NOT NULL, base_unit_price numeric(14,2) NOT NULL, base_subtotal numeric(14,2) NOT NULL, processing_unit_amount numeric(14,2) NOT NULL, urgent_percent numeric(7,2) NOT NULL, urgency_surcharge numeric(14,2) NOT NULL, line_total numeric(14,2) NOT NULL, price_fixed_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY(lab_organization_id,work_order_id,line_no), FOREIGN KEY(lab_organization_id,work_order_id,line_no) REFERENCES public.lab_partner_work_order_items(lab_organization_id,work_order_id,line_no) ON DELETE CASCADE
);
CREATE TABLE IF NOT EXISTS public.lab_work_order_approval_events (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, lab_organization_id uuid NOT NULL, work_order_id bigint NOT NULL, state text NOT NULL CHECK(state IN ('pending','approved','rejected')), reason text, actor_user_id uuid, created_at timestamptz NOT NULL DEFAULT now(),
  FOREIGN KEY(lab_organization_id,work_order_id) REFERENCES public.lab_work_orders(lab_organization_id,id) ON DELETE CASCADE
);
-- Price decisions and ownership checks stay inside one database transaction.
INSERT INTO public.role_permissions (
 role,work_order_scope,can_view_work_orders,can_view_production,can_view_partners,
 can_view_technicians,can_create_work_orders,can_edit_all_work_orders,
 can_edit_own_stage_status,can_assign_technicians,can_view_client_pricing,
 can_view_other_technician_costs,can_view_own_technician_cost,can_edit_payment_status,
 can_edit_global_status,can_access_backend,ai_flow,active,can_edit_partner_work_orders
) SELECT 'Lab Partner','Own',true,false,false,false,true,false,false,false,true,
 false,false,false,false,false,null,true,true
WHERE NOT EXISTS (SELECT 1 FROM public.role_permissions WHERE lower(role) IN ('lab partner','lab_partner'));

CREATE OR REPLACE FUNCTION public.lab_partner_identity(p_lab uuid)
RETURNS TABLE(partner_id uuid, partner_name text)
LANGUAGE plpgsql STABLE SECURITY DEFINER SET search_path=public AS $$
BEGIN
 IF public.effective_lab_role(p_lab) NOT IN ('lab partner','lab_partner') THEN
   RAISE EXCEPTION 'Lab Partner access denied';
 END IF;
 RETURN QUERY SELECT p.id,p.name FROM public.lab_partner_user_links l
 JOIN public.lab_partners p ON p.id=l.partner_id AND p.lab_organization_id=l.lab_organization_id AND p.active
 WHERE l.lab_organization_id=p_lab AND l.user_id=auth.uid();
END $$;
REVOKE ALL ON FUNCTION public.lab_partner_identity(uuid) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.lab_partner_identity(uuid) TO authenticated;

CREATE OR REPLACE FUNCTION public.lab_partner_can_access_order(p_lab uuid,p_order bigint)
RETURNS boolean LANGUAGE sql STABLE SECURITY DEFINER SET search_path=public AS $$
 SELECT public.effective_lab_role(p_lab) IN ('lab partner','lab_partner')
 AND EXISTS (SELECT 1 FROM public.lab_work_orders o
 JOIN public.lab_partner_user_links l ON l.lab_organization_id=o.lab_organization_id AND l.partner_id=o.partner_id
 JOIN public.lab_partners p ON p.id=l.partner_id AND p.lab_organization_id=l.lab_organization_id AND p.active
 WHERE o.lab_organization_id=p_lab AND o.id=p_order AND l.user_id=auth.uid());
$$;
REVOKE ALL ON FUNCTION public.lab_partner_can_access_order(uuid,bigint) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.lab_partner_can_access_order(uuid,bigint) TO authenticated;

CREATE OR REPLACE FUNCTION public.lab_partner_quote(p_lab uuid,p_items jsonb,p_deadline_at timestamptz)
RETURNS jsonb LANGUAGE plpgsql STABLE SECURITY DEFINER SET search_path=public AS $$
DECLARE
 v_partner uuid; v_name text; v_default text; v_hours integer;
 v_urgent boolean; v_item jsonb; v_type public.lab_work_types%rowtype;
 v_price public.lab_contract_work_prices%rowtype;
 v_percent numeric; v_processing numeric; v_base numeric; v_amount numeric;
 v_surcharge numeric; v_total numeric:=0; v_lines jsonb:='[]'::jsonb;
 v_qty integer; v_selected boolean; v_index integer:=0;
BEGIN
 SELECT partner_id,partner_name INTO v_partner,v_name FROM public.lab_partner_identity(p_lab);
 IF v_partner IS NULL THEN RAISE EXCEPTION 'Lab Partner mapping is missing'; END IF;
 IF p_deadline_at IS NULL OR p_deadline_at <= now() THEN RAISE EXCEPTION 'Deadline must be in the future'; END IF;
 IF p_items IS NULL OR jsonb_typeof(p_items) <> 'array' OR jsonb_array_length(p_items) NOT BETWEEN 1 AND 100 THEN
   RAISE EXCEPTION 'Provide 1 to 100 commercial lines';
 END IF;
 SELECT default_contract,urgent_window_hours INTO v_default,v_hours
 FROM public.lab_order_pricing_settings WHERE lab_organization_id=p_lab;
 v_default:=coalesce(nullif(trim(v_default),''),'General');
 v_hours:=coalesce(v_hours,24);
 v_urgent:=(p_deadline_at-now()) < make_interval(hours=>v_hours);
 FOR v_item IN SELECT value FROM jsonb_array_elements(p_items) LOOP
   v_index:=v_index+1;
   IF jsonb_typeof(v_item) <> 'object' OR coalesce(v_item->>'quantity','') !~ '^[1-9][0-9]{0,4}$'
      OR jsonb_typeof(v_item->'processing_requested') NOT IN ('boolean','null')
      OR length(coalesce(v_item->>'color',''))>120 THEN
      RAISE EXCEPTION 'Invalid commercial line %',v_index;
   END IF;
   v_qty:=(v_item->>'quantity')::integer;
   v_selected:=coalesce((v_item->>'processing_requested')::boolean,false);
   SELECT * INTO v_type FROM public.lab_work_types wt
   WHERE wt.lab_organization_id=p_lab AND wt.active
     AND lower(trim(wt.tip_lucrare))=lower(trim(v_item->>'work_type'))
   ORDER BY wt.id LIMIT 1;
   IF NOT FOUND THEN RAISE EXCEPTION 'Invalid active work type on line %',v_index; END IF;
   IF v_selected AND NOT v_type.processing_enabled THEN
     RAISE EXCEPTION 'Processing is not enabled for %',v_type.tip_lucrare;
   END IF;
   SELECT * INTO v_price FROM public.lab_contract_work_prices cp
   WHERE cp.lab_organization_id=p_lab AND lower(trim(cp.tip_lucrare))=lower(trim(v_type.tip_lucrare))
     AND lower(trim(cp.contract)) IN (lower(trim(v_name)),lower(trim(v_default)))
   ORDER BY CASE WHEN lower(trim(cp.contract))=lower(trim(v_name)) THEN 0 ELSE 1 END,cp.id LIMIT 1;
   IF NOT FOUND THEN RAISE EXCEPTION 'Missing contract price for %',v_type.tip_lucrare; END IF;
   SELECT coalesce(v_price.urgent_percent_override,d.urgent_percent,0),
          coalesce(v_price.processing_amount_override,d.processing_amount,0)
   INTO v_percent,v_processing FROM (SELECT 1) s
   LEFT JOIN public.lab_contract_pricing_defaults d
     ON d.lab_organization_id=p_lab AND lower(trim(d.contract))=lower(trim(v_price.contract));
   v_percent:=CASE WHEN v_urgent THEN v_percent ELSE 0 END;
   v_processing:=CASE WHEN v_selected THEN v_processing ELSE 0 END;
   v_base:=round(v_price.pret*v_qty,2);
   v_amount:=round(v_processing*v_qty,2);
   v_surcharge:=round((v_base+v_amount)*v_percent/100,2);
   v_total:=v_total+v_base+v_amount+v_surcharge;
   v_lines:=v_lines||jsonb_build_array(jsonb_build_object(
     'line_no',v_index,'work_type',v_type.tip_lucrare,'color',nullif(trim(coalesce(v_item->>'color','')),''),
     'quantity',v_qty,'processing_requested',v_selected,'contract',v_price.contract,
     'base_unit_price',v_price.pret,'base_subtotal',v_base,
     'processing_unit_amount',v_processing,'processing_subtotal',v_amount,
     'urgent_percent',v_percent,'urgency_surcharge',v_surcharge,
     'line_total',v_base+v_amount+v_surcharge));
 END LOOP;
 RETURN jsonb_build_object('partner_id',v_partner,'partner_name',v_name,
  'urgent',v_urgent,'urgent_window_hours',v_hours,'lines',v_lines,
  'final_price',round(v_total,2));
END $$;
REVOKE ALL ON FUNCTION public.lab_partner_quote(uuid,jsonb,timestamptz) FROM PUBLIC;

CREATE OR REPLACE FUNCTION public.estimate_lab_partner_work_order_price(p_lab uuid,p_items jsonb,p_deadline_at timestamptz)
RETURNS jsonb LANGUAGE sql STABLE SECURITY DEFINER SET search_path=public AS $$
 SELECT public.lab_partner_quote(p_lab,p_items,p_deadline_at);
$$;
REVOKE ALL ON FUNCTION public.estimate_lab_partner_work_order_price(uuid,jsonb,timestamptz) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.estimate_lab_partner_work_order_price(uuid,jsonb,timestamptz) TO authenticated;

CREATE OR REPLACE FUNCTION public.save_lab_partner_lines(p_lab uuid,p_order bigint,p_quote jsonb,p_note text)
RETURNS void LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$
DECLARE v_line jsonb;
BEGIN
 IF NOT public.lab_partner_can_access_order(p_lab,p_order) THEN RAISE EXCEPTION 'Order access denied'; END IF;
 DELETE FROM public.lab_partner_work_order_items WHERE lab_organization_id=p_lab AND work_order_id=p_order;
 FOR v_line IN SELECT value FROM jsonb_array_elements(p_quote->'lines') LOOP
   INSERT INTO public.lab_partner_work_order_items
   (lab_organization_id,work_order_id,line_no,work_type,color,quantity,processing_requested,note)
   VALUES(p_lab,p_order,(v_line->>'line_no')::integer,v_line->>'work_type',v_line->>'color',
     (v_line->>'quantity')::integer,(v_line->>'processing_requested')::boolean,
     CASE WHEN (v_line->>'line_no')::integer=1 THEN nullif(left(trim(coalesce(p_note,'')),2000),'') END);
   INSERT INTO public.lab_partner_work_order_price_lines
   (lab_organization_id,work_order_id,line_no,contract,base_unit_price,base_subtotal,
    processing_unit_amount,urgent_percent,urgency_surcharge,line_total)
   VALUES(p_lab,p_order,(v_line->>'line_no')::integer,v_line->>'contract',
    (v_line->>'base_unit_price')::numeric,(v_line->>'base_subtotal')::numeric,
    (v_line->>'processing_unit_amount')::numeric,(v_line->>'urgent_percent')::numeric,
    (v_line->>'urgency_surcharge')::numeric,(v_line->>'line_total')::numeric);
 END LOOP;
END $$;
REVOKE ALL ON FUNCTION public.save_lab_partner_lines(uuid,bigint,jsonb,text) FROM PUBLIC,authenticated;

CREATE OR REPLACE FUNCTION public.create_lab_partner_work_order(p_lab uuid,p_deadline_at timestamptz,p_items jsonb,p_note text DEFAULT NULL)
RETURNS bigint LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$
DECLARE v_id bigint; v_quote jsonb;
BEGIN
 v_quote:=public.lab_partner_quote(p_lab,p_items,p_deadline_at);
 v_id:=public.next_lab_work_order_id(p_lab);
 INSERT INTO public.lab_work_orders
 (lab_organization_id,id,deadline,deadline_at,status,nume_partener,partner_id,contract,
  order_origin,approval_state,created_by_user_id,created_at,updated_by_user_id,updated_at,
  data_receptie,snapshot_list_price,snapshot_final_price,price_source,price_fixed_at)
 VALUES(p_lab,v_id,(p_deadline_at AT TIME ZONE 'Europe/Bucharest')::date,p_deadline_at,
  'Not Started',v_quote->>'partner_name',(v_quote->>'partner_id')::uuid,
  v_quote->'lines'->0->>'contract','lab_partner','pending',
  public.current_legacy_user_id(),now(),public.current_legacy_user_id(),now(),now(),
  (v_quote->>'final_price')::numeric,(v_quote->>'final_price')::numeric,'lab_partner_snapshot',now());
 PERFORM public.save_lab_partner_lines(p_lab,v_id,v_quote,p_note);
 INSERT INTO public.lab_work_order_approval_events(lab_organization_id,work_order_id,state,actor_user_id)
 VALUES(p_lab,v_id,'pending',auth.uid());
 RETURN v_id;
END $$;
REVOKE ALL ON FUNCTION public.create_lab_partner_work_order(uuid,timestamptz,jsonb,text) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.create_lab_partner_work_order(uuid,timestamptz,jsonb,text) TO authenticated;

CREATE OR REPLACE FUNCTION public.resubmit_lab_partner_work_order
(p_lab uuid,p_order bigint,p_deadline_at timestamptz,p_items jsonb,p_note text DEFAULT NULL)
RETURNS boolean LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$
DECLARE v_order public.lab_work_orders%rowtype; v_quote jsonb;
BEGIN
 SELECT * INTO v_order FROM public.lab_work_orders
 WHERE lab_organization_id=p_lab AND id=p_order FOR UPDATE;
 IF NOT FOUND OR NOT public.lab_partner_can_access_order(p_lab,p_order)
   OR v_order.order_origin<>'lab_partner' OR v_order.approval_state<>'rejected'
   OR v_order.locked OR lower(trim(v_order.status))<>'not started' THEN
   RAISE EXCEPTION 'Order cannot be resubmitted';
 END IF;
 v_quote:=public.lab_partner_quote(p_lab,p_items,p_deadline_at);
 UPDATE public.lab_work_orders SET
   deadline=(p_deadline_at AT TIME ZONE 'Europe/Bucharest')::date,deadline_at=p_deadline_at,
   approval_state='pending',approval_reason=NULL,approval_reviewed_at=NULL,
   approval_reviewed_by_user_id=NULL,snapshot_list_price=(v_quote->>'final_price')::numeric,
   snapshot_final_price=(v_quote->>'final_price')::numeric,price_fixed_at=now(),
   updated_by_user_id=public.current_legacy_user_id(),updated_at=now()
 WHERE lab_organization_id=p_lab AND id=p_order;
 PERFORM public.save_lab_partner_lines(p_lab,p_order,v_quote,p_note);
 INSERT INTO public.lab_work_order_approval_events(lab_organization_id,work_order_id,state,actor_user_id)
 VALUES(p_lab,p_order,'pending',auth.uid());
 RETURN true;
END $$;
REVOKE ALL ON FUNCTION public.resubmit_lab_partner_work_order(uuid,bigint,timestamptz,jsonb,text) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.resubmit_lab_partner_work_order(uuid,bigint,timestamptz,jsonb,text) TO authenticated;

-- A pending or refused submission cannot enter production or be locked.
CREATE OR REPLACE FUNCTION public.guard_external_order_production()
RETURNS trigger LANGUAGE plpgsql SET search_path=public AS $$
BEGIN
 IF NEW.order_origin IN ('doctor','lab_partner') AND NEW.approval_state<>'approved' AND
   (NEW.locked OR NEW.status<>'Not Started' OR
    coalesce(NEW.status_model,'Not Started')<>'Not Started' OR
    coalesce(NEW.status_modelare,'Not Started')<>'Not Started' OR
    coalesce(NEW.status_cer_fin,'Not Started')<>'Not Started' OR
    NEW.tehnician_model IS NOT NULL OR NEW.tehnician1_modelare IS NOT NULL OR
    NEW.tehnician2_cer_fin IS NOT NULL OR NEW.archived_at IS NOT NULL) THEN
   RAISE EXCEPTION 'Order must be approved before production';
 END IF;
 RETURN NEW;
END $$;
DROP TRIGGER IF EXISTS guard_external_order_production ON public.lab_work_orders;
CREATE TRIGGER guard_external_order_production BEFORE INSERT OR UPDATE ON public.lab_work_orders
FOR EACH ROW EXECUTE FUNCTION public.guard_external_order_production();

-- Existing Doctor RPCs still insert through lab_work_orders. Stamp their origin
-- before the production guard, including clients using the legacy date RPC.
CREATE OR REPLACE FUNCTION public.stamp_external_order_origin()
RETURNS trigger LANGUAGE plpgsql SET search_path=public AS $$
BEGIN
 IF public.effective_lab_role(NEW.lab_organization_id)='doctor' AND NEW.order_origin='internal' THEN
   NEW.order_origin:='doctor'; NEW.approval_state:='pending';
   SELECT id INTO NEW.partner_id FROM public.lab_partners
   WHERE lab_organization_id=NEW.lab_organization_id AND active
     AND lower(trim(name))=lower(trim(NEW.nume_partener)) LIMIT 1;
   IF NEW.partner_id IS NULL THEN RAISE EXCEPTION 'Doctor partner is not in the active catalog'; END IF;
 END IF;
 IF NEW.deadline_at IS NULL AND NEW.deadline IS NOT NULL THEN
   NEW.deadline_at:=(NEW.deadline::timestamp+interval '23 hours 59 minutes') AT TIME ZONE 'Europe/Bucharest';
 END IF;
 RETURN NEW;
END $$;
DROP TRIGGER IF EXISTS stamp_external_order_origin ON public.lab_work_orders;
CREATE TRIGGER stamp_external_order_origin BEFORE INSERT ON public.lab_work_orders
FOR EACH ROW EXECUTE FUNCTION public.stamp_external_order_origin();
UPDATE public.lab_work_orders SET deadline_at=(deadline::timestamp+interval '23 hours 59 minutes') AT TIME ZONE 'Europe/Bucharest'
WHERE deadline_at IS NULL AND deadline IS NOT NULL;

CREATE OR REPLACE FUNCTION public.review_external_work_order
(p_lab uuid,p_order bigint,p_decision text,p_reason text DEFAULT NULL)
RETURNS boolean LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$
DECLARE v_state text:=lower(trim(p_decision)); v_reason text:=nullif(trim(coalesce(p_reason,'')),'');
BEGIN
 IF NOT public.is_lab_management(p_lab) THEN RAISE EXCEPTION 'Management access denied'; END IF;
 IF v_state NOT IN ('approve','reject') OR length(coalesce(v_reason,''))>1000 THEN
   RAISE EXCEPTION 'Invalid review decision or reason';
 END IF;
 UPDATE public.lab_work_orders SET
   approval_state=CASE WHEN v_state='approve' THEN 'approved' ELSE 'rejected' END,
   approval_reviewed_at=now(),approval_reviewed_by_user_id=auth.uid(),approval_reason=v_reason,
   updated_at=now()
 WHERE lab_organization_id=p_lab AND id=p_order AND order_origin IN ('doctor','lab_partner')
   AND approval_state='pending';
 IF NOT FOUND THEN RAISE EXCEPTION 'Order is not awaiting approval'; END IF;
 INSERT INTO public.lab_work_order_approval_events
 (lab_organization_id,work_order_id,state,reason,actor_user_id)
 VALUES(p_lab,p_order,CASE WHEN v_state='approve' THEN 'approved' ELSE 'rejected' END,v_reason,auth.uid());
 RETURN true;
END $$;
REVOKE ALL ON FUNCTION public.review_external_work_order(uuid,bigint,text,text) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.review_external_work_order(uuid,bigint,text,text) TO authenticated;

CREATE OR REPLACE FUNCTION public.list_lab_partner_work_orders(p_lab uuid)
RETURNS jsonb LANGUAGE plpgsql STABLE SECURITY DEFINER SET search_path=public AS $$
DECLARE v_partner uuid; v_rows jsonb;
BEGIN
 SELECT partner_id INTO v_partner FROM public.lab_partner_identity(p_lab);
 IF v_partner IS NULL THEN RAISE EXCEPTION 'Lab Partner mapping is missing'; END IF;
 SELECT coalesce(jsonb_agg(jsonb_build_object(
  'id',o.id,'deadline',o.deadline,'deadline_at',o.deadline_at,
  'status',o.status,'partner',o.nume_partener,'approval_state',o.approval_state,
  'approval_reason',o.approval_reason,'approval_reviewed_at',o.approval_reviewed_at,
  'final_price',o.snapshot_final_price,'created_at',o.created_at,
  'items',coalesce((SELECT jsonb_agg(to_jsonb(i) ORDER BY i.line_no)
    FROM public.lab_partner_work_order_items i WHERE i.lab_organization_id=p_lab AND i.work_order_id=o.id),'[]'::jsonb)
 ) ORDER BY o.id DESC),'[]'::jsonb) INTO v_rows
 FROM public.lab_work_orders o WHERE o.lab_organization_id=p_lab AND o.partner_id=v_partner
   AND o.order_origin='lab_partner' AND o.archived_at IS NULL;
 RETURN v_rows;
END $$;
REVOKE ALL ON FUNCTION public.list_lab_partner_work_orders(uuid) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.list_lab_partner_work_orders(uuid) TO authenticated;

CREATE OR REPLACE FUNCTION public.get_lab_partner_work_order(p_lab uuid,p_order bigint)
RETURNS jsonb LANGUAGE plpgsql STABLE SECURITY DEFINER SET search_path=public AS $$
DECLARE v_result jsonb;
BEGIN
 IF NOT public.lab_partner_can_access_order(p_lab,p_order) AND NOT public.is_lab_management(p_lab) THEN
   RAISE EXCEPTION 'Order access denied';
 END IF;
 SELECT jsonb_build_object('id',o.id,'deadline_at',o.deadline_at,'status',o.status,
  'approval_state',o.approval_state,'approval_reason',o.approval_reason,
  'approval_reviewed_at',o.approval_reviewed_at,'final_price',o.snapshot_final_price,
  'items',coalesce((SELECT jsonb_agg(to_jsonb(i) ORDER BY i.line_no)
      FROM public.lab_partner_work_order_items i WHERE i.lab_organization_id=p_lab AND i.work_order_id=p_order),'[]'::jsonb),
  'price_lines',coalesce((SELECT jsonb_agg(to_jsonb(l) ORDER BY l.line_no)
      FROM public.lab_partner_work_order_price_lines l WHERE l.lab_organization_id=p_lab AND l.work_order_id=p_order),'[]'::jsonb))
 INTO v_result FROM public.lab_work_orders o WHERE o.lab_organization_id=p_lab AND o.id=p_order
  AND o.order_origin='lab_partner';
 RETURN v_result;
END $$;
REVOKE ALL ON FUNCTION public.get_lab_partner_work_order(uuid,bigint) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.get_lab_partner_work_order(uuid,bigint) TO authenticated;

CREATE OR REPLACE FUNCTION public.get_work_order_approval_summary(p_lab uuid,p_orders bigint[])
RETURNS jsonb LANGUAGE plpgsql STABLE SECURITY DEFINER SET search_path=public AS $$
DECLARE v_result jsonb;
BEGIN
 IF auth.uid() IS NULL OR coalesce(array_length(p_orders,1),0)>200 THEN RAISE EXCEPTION 'Invalid request'; END IF;
 SELECT coalesce(jsonb_object_agg(o.id::text,jsonb_build_object(
  'state',o.approval_state,'origin',o.order_origin,'reason',o.approval_reason,
  'reviewed_at',o.approval_reviewed_at,'reviewed_by',o.approval_reviewed_by_user_id,
  'deadline_at',o.deadline_at)),'{}'::jsonb)
 INTO v_result FROM public.lab_work_orders o WHERE o.lab_organization_id=p_lab
 AND o.id=ANY(p_orders) AND public.can_access_work_order(p_lab,o.id);
 RETURN v_result;
END $$;
REVOKE ALL ON FUNCTION public.get_work_order_approval_summary(uuid,bigint[]) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.get_work_order_approval_summary(uuid,bigint[]) TO authenticated;

CREATE OR REPLACE FUNCTION public.can_access_work_order(p_lab_organization_id uuid,p_work_order_id bigint)
RETURNS boolean LANGUAGE plpgsql STABLE SECURITY DEFINER SET search_path=public AS $$
DECLARE v_order public.lab_work_orders%rowtype; v_technician text;
BEGIN
 SELECT * INTO v_order FROM public.lab_work_orders WHERE lab_organization_id=p_lab_organization_id
  AND id=p_work_order_id;
 IF NOT FOUND THEN RETURN false; END IF;
 IF public.is_lab_management(p_lab_organization_id) OR public.is_lab_dashboard(p_lab_organization_id) THEN RETURN true; END IF;
 IF public.lab_partner_can_access_order(p_lab_organization_id,p_work_order_id) THEN RETURN true; END IF;
 IF public.is_lab_technician(p_lab_organization_id) THEN
   v_technician:=lower(trim(coalesce(public.current_technician_name(),'')));
   RETURN v_order.approval_state='approved' AND v_technician<>'' AND v_technician IN (
    lower(trim(coalesce(v_order.tehnician_model,''))),lower(trim(coalesce(v_order.tehnician1_modelare,''))),
    lower(trim(coalesce(v_order.tehnician2_cer_fin,''))));
 END IF;
 IF public.is_connected_doctor_for_lab(p_lab_organization_id) THEN
   RETURN public.doctor_matches_partner(v_order.nume_partener);
 END IF;
 RETURN false;
END $$;

ALTER TABLE public.lab_partner_user_links ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.lab_order_pricing_settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.lab_contract_pricing_defaults ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.lab_partner_work_order_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.lab_partner_work_order_price_lines ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.lab_work_order_approval_events ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS lab_order_pricing_settings_management ON public.lab_order_pricing_settings;
CREATE POLICY lab_order_pricing_settings_management ON public.lab_order_pricing_settings
FOR ALL TO authenticated USING (public.is_lab_management(lab_organization_id))
WITH CHECK (public.is_lab_management(lab_organization_id));
DROP POLICY IF EXISTS lab_contract_pricing_defaults_management ON public.lab_contract_pricing_defaults;
CREATE POLICY lab_contract_pricing_defaults_management ON public.lab_contract_pricing_defaults
FOR ALL TO authenticated USING (public.is_lab_management(lab_organization_id))
WITH CHECK (public.is_lab_management(lab_organization_id));
GRANT SELECT,INSERT,UPDATE,DELETE ON public.lab_order_pricing_settings,public.lab_contract_pricing_defaults TO authenticated;

ALTER TABLE public.lab_work_order_price_lines
 ADD COLUMN IF NOT EXISTS urgent_percent numeric(7,2) NOT NULL DEFAULT 0,
 ADD COLUMN IF NOT EXISTS urgency_surcharge numeric(14,2) NOT NULL DEFAULT 0,
 ADD COLUMN IF NOT EXISTS base_line_total numeric(14,2);

CREATE OR REPLACE FUNCTION public.apply_doctor_order_urgency(p_lab uuid,p_order bigint,p_deadline_at timestamptz)
RETURNS void LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$
DECLARE v_hours integer; v_urgent boolean; v_total numeric; v_line public.lab_work_order_price_lines%rowtype; v_percent numeric;
BEGIN
 IF public.effective_lab_role(p_lab)<>'doctor' OR NOT public.can_access_work_order(p_lab,p_order) THEN
   RAISE EXCEPTION 'Doctor access denied';
 END IF;
 IF p_deadline_at IS NULL OR p_deadline_at<=now() THEN RAISE EXCEPTION 'Deadline must be in the future'; END IF;
 SELECT urgent_window_hours INTO v_hours FROM public.lab_order_pricing_settings
 WHERE lab_organization_id=p_lab;
 v_urgent:=(p_deadline_at-now()) < make_interval(hours=>coalesce(v_hours,24));
 FOR v_line IN SELECT * FROM public.lab_work_order_price_lines
 WHERE lab_organization_id=p_lab AND work_order_id=p_order LOOP
   SELECT coalesce(cp.urgent_percent_override,d.urgent_percent,0) INTO v_percent
   FROM (SELECT 1) s
   LEFT JOIN public.lab_contract_pricing_defaults d ON d.lab_organization_id=p_lab
     AND lower(trim(d.contract))=lower(trim(v_line.contract))
   LEFT JOIN public.lab_contract_work_prices cp ON cp.lab_organization_id=p_lab
     AND lower(trim(cp.contract))=lower(trim(v_line.contract))
     AND lower(trim(cp.tip_lucrare))=lower(trim(v_line.work_type))
   ORDER BY cp.id LIMIT 1;
   v_percent:=CASE WHEN v_urgent THEN coalesce(v_percent,0) ELSE 0 END;
   UPDATE public.lab_work_order_price_lines SET
     base_line_total=coalesce(v_line.base_line_total,v_line.line_total),
     urgent_percent=v_percent,
     urgency_surcharge=coalesce(round(coalesce(v_line.base_line_total,v_line.line_total)*v_percent/100,2),0),
     line_total=CASE WHEN v_line.line_total IS NULL THEN NULL ELSE
       coalesce(v_line.base_line_total,v_line.line_total)+round(coalesce(v_line.base_line_total,v_line.line_total)*v_percent/100,2) END
   WHERE lab_organization_id=p_lab AND work_order_id=p_order
     AND work_type=v_line.work_type AND billing_scope=v_line.billing_scope;
 END LOOP;
 SELECT CASE WHEN count(*) FILTER (WHERE line_total IS NULL)>0 THEN NULL ELSE sum(line_total) END
 INTO v_total FROM public.lab_work_order_price_lines
 WHERE lab_organization_id=p_lab AND work_order_id=p_order;
 UPDATE public.lab_work_orders SET deadline=(p_deadline_at AT TIME ZONE 'Europe/Bucharest')::date,
 deadline_at=p_deadline_at,snapshot_list_price=v_total,snapshot_final_price=v_total,
 price_fixed_at=now() WHERE lab_organization_id=p_lab AND id=p_order;
END $$;
REVOKE ALL ON FUNCTION public.apply_doctor_order_urgency(uuid,bigint,timestamptz) FROM PUBLIC,authenticated;

CREATE OR REPLACE FUNCTION public.create_doctor_work_order_v2
(p_lab uuid,p_deadline_at timestamptz,p_nume_pacient text,p_items jsonb,p_case jsonb DEFAULT '{}'::jsonb)
RETURNS bigint LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$
DECLARE v_id bigint;
BEGIN
 IF public.effective_lab_role(p_lab)<>'doctor' THEN RAISE EXCEPTION 'Doctor access denied'; END IF;
 v_id:=public.create_work_order(p_lab,(p_deadline_at AT TIME ZONE 'Europe/Bucharest')::date,
 p_nume_pacient,p_items,NULL,'General','Not Started',0,NULL,p_case);
 PERFORM public.apply_doctor_order_urgency(p_lab,v_id,p_deadline_at);
 RETURN v_id;
END $$;
REVOKE ALL ON FUNCTION public.create_doctor_work_order_v2(uuid,timestamptz,text,jsonb,jsonb) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.create_doctor_work_order_v2(uuid,timestamptz,text,jsonb,jsonb) TO authenticated;

CREATE OR REPLACE FUNCTION public.estimate_doctor_work_order_v2
(p_lab uuid,p_deadline_at timestamptz,p_items jsonb)
RETURNS jsonb LANGUAGE plpgsql STABLE SECURITY DEFINER SET search_path=public AS $$
DECLARE v_est jsonb; v_lines jsonb:='[]'::jsonb; v_line jsonb;
 v_hours integer; v_urgent boolean; v_percent numeric; v_subtotal numeric; v_surcharge numeric; v_total numeric:=0;
BEGIN
 IF public.effective_lab_role(p_lab)<>'doctor' THEN RAISE EXCEPTION 'Doctor access denied'; END IF;
 IF p_deadline_at IS NULL OR p_deadline_at<=now() THEN RAISE EXCEPTION 'Deadline must be in the future'; END IF;
 v_est:=public.estimate_work_order_items(p_lab,NULL,'General',p_items,0);
 SELECT urgent_window_hours INTO v_hours FROM public.lab_order_pricing_settings WHERE lab_organization_id=p_lab;
 v_hours:=coalesce(v_hours,24);
 v_urgent:=(p_deadline_at-now())<make_interval(hours=>v_hours);
 FOR v_line IN SELECT value FROM jsonb_array_elements(v_est->'lines') LOOP
   SELECT coalesce(cp.urgent_percent_override,d.urgent_percent,0) INTO v_percent
   FROM (SELECT 1) s
   LEFT JOIN public.lab_contract_pricing_defaults d ON d.lab_organization_id=p_lab
    AND lower(trim(d.contract))=lower(trim(v_line->>'contract'))
   LEFT JOIN public.lab_contract_work_prices cp ON cp.lab_organization_id=p_lab
    AND lower(trim(cp.contract))=lower(trim(v_line->>'contract'))
    AND lower(trim(cp.tip_lucrare))=lower(trim(v_line->>'work_type'))
   ORDER BY cp.id LIMIT 1;
   v_percent:=CASE WHEN v_urgent THEN coalesce(v_percent,0) ELSE 0 END;
   v_subtotal:=(v_line->>'subtotal')::numeric;
   v_surcharge:=round(v_subtotal*v_percent/100,2);
   v_total:=v_total+v_subtotal+v_surcharge;
   v_lines:=v_lines||jsonb_build_array(v_line||jsonb_build_object(
    'base_subtotal',v_subtotal,'urgent_percent',v_percent,
    'urgency_surcharge',v_surcharge,'subtotal',v_subtotal+v_surcharge));
 END LOOP;
 RETURN v_est||jsonb_build_object('lines',v_lines,'list_price',round(v_total,2),
   'final_price',round(v_total,2),'urgent',v_urgent,'urgent_window_hours',v_hours);
END $$;
REVOKE ALL ON FUNCTION public.estimate_doctor_work_order_v2(uuid,timestamptz,jsonb) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.estimate_doctor_work_order_v2(uuid,timestamptz,jsonb) TO authenticated;

CREATE OR REPLACE FUNCTION public.resubmit_doctor_work_order
(p_lab uuid,p_order bigint,p_deadline_at timestamptz,p_nume_pacient text,p_items jsonb,p_case jsonb DEFAULT '{}'::jsonb)
RETURNS boolean LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$
DECLARE v_order public.lab_work_orders%rowtype;
BEGIN
 SELECT * INTO v_order FROM public.lab_work_orders WHERE lab_organization_id=p_lab AND id=p_order FOR UPDATE;
 IF NOT FOUND OR public.effective_lab_role(p_lab)<>'doctor' OR
   NOT public.doctor_matches_partner(v_order.nume_partener) OR
   v_order.order_origin<>'doctor' OR v_order.approval_state<>'rejected' OR
   v_order.locked OR v_order.status<>'Not Started' THEN
   RAISE EXCEPTION 'Doctor order cannot be resubmitted';
 END IF;
 PERFORM public.update_doctor_work_order(p_lab,p_order,
  (p_deadline_at AT TIME ZONE 'Europe/Bucharest')::date,p_nume_pacient,p_items,p_case);
 PERFORM public.apply_doctor_order_urgency(p_lab,p_order,p_deadline_at);
 UPDATE public.lab_work_orders SET approval_state='pending',approval_reason=NULL,
  approval_reviewed_at=NULL,approval_reviewed_by_user_id=NULL
 WHERE lab_organization_id=p_lab AND id=p_order;
 INSERT INTO public.lab_work_order_approval_events(lab_organization_id,work_order_id,state,actor_user_id)
 VALUES(p_lab,p_order,'pending',auth.uid());
 RETURN true;
END $$;
REVOKE ALL ON FUNCTION public.resubmit_doctor_work_order(uuid,bigint,timestamptz,text,jsonb,jsonb) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.resubmit_doctor_work_order(uuid,bigint,timestamptz,text,jsonb,jsonb) TO authenticated;

CREATE OR REPLACE FUNCTION public.log_doctor_submission()
RETURNS trigger LANGUAGE plpgsql SET search_path=public AS $$
BEGIN
 IF NEW.order_origin='doctor' AND NEW.approval_state='pending' THEN
  INSERT INTO public.lab_work_order_approval_events(lab_organization_id,work_order_id,state,actor_user_id)
  VALUES(NEW.lab_organization_id,NEW.id,'pending',auth.uid());
 END IF;
 RETURN NEW;
END $$;
DROP TRIGGER IF EXISTS log_doctor_submission ON public.lab_work_orders;
CREATE TRIGGER log_doctor_submission AFTER INSERT ON public.lab_work_orders
FOR EACH ROW EXECUTE FUNCTION public.log_doctor_submission();

CREATE OR REPLACE FUNCTION public.set_internal_work_order_deadline_at
(p_lab uuid,p_order bigint,p_deadline_at timestamptz)
RETURNS boolean LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$
DECLARE v_role text:=public.effective_lab_role(p_lab); v_created text;
BEGIN
 IF p_deadline_at IS NULL OR p_deadline_at<=now() THEN RAISE EXCEPTION 'Deadline must be in the future'; END IF;
 SELECT created_by_user_id INTO v_created FROM public.lab_work_orders
 WHERE lab_organization_id=p_lab AND id=p_order AND approval_state='approved'
   AND (order_origin='internal' OR public.is_lab_management(p_lab)) FOR UPDATE;
 IF NOT FOUND OR (v_role NOT IN ('admin','manager') AND
   (v_role<>'technician' OR v_created IS DISTINCT FROM public.current_legacy_user_id())) THEN
   RAISE EXCEPTION 'Deadline update denied';
 END IF;
 UPDATE public.lab_work_orders SET deadline_at=p_deadline_at,
   deadline=(p_deadline_at AT TIME ZONE 'Europe/Bucharest')::date
 WHERE lab_organization_id=p_lab AND id=p_order;
 RETURN true;
END $$;
REVOKE ALL ON FUNCTION public.set_internal_work_order_deadline_at(uuid,bigint,timestamptz) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.set_internal_work_order_deadline_at(uuid,bigint,timestamptz) TO authenticated;

ALTER TABLE public.email_notification_queue DROP CONSTRAINT IF EXISTS email_notification_queue_event_kind_check;
ALTER TABLE public.email_notification_queue ADD CONSTRAINT email_notification_queue_event_kind_check
CHECK(event_kind IN ('new_work_order','stage_status','work_order_status','assignment','approval_state'));

CREATE OR REPLACE FUNCTION public.enqueue_approval_state_email()
RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path='' AS $$
BEGIN
 IF NEW.approval_state IS DISTINCT FROM OLD.approval_state
   AND NEW.order_origin IN ('doctor','lab_partner') AND NEW.archived_at IS NULL THEN
  INSERT INTO public.email_notification_queue
   (lab_organization_id,work_order_id,recipient_id,event_kind,old_status,new_status)
  SELECT NEW.lab_organization_id,NEW.id,p.id,'approval_state',OLD.approval_state,NEW.approval_state
  FROM public.profiles p WHERE p.notify_new_work_order
   AND public.email_notification_recipient_allowed(p.id,NEW.lab_organization_id,NEW.id,'approval_state',NULL)
  ON CONFLICT DO NOTHING;
 END IF;
 RETURN NEW;
END $$;
DROP TRIGGER IF EXISTS work_order_approval_email ON public.lab_work_orders;
CREATE TRIGGER work_order_approval_email AFTER UPDATE OF approval_state ON public.lab_work_orders
FOR EACH ROW EXECUTE FUNCTION public.enqueue_approval_state_email();

-- Include processing eligibility in the reference data returned to the commercial form.
-- Flowrise Supabase function: public.get_work_order_reference_data(p_lab_organization_id uuid)
-- Generated from the Supabase schema snapshot dated 2026-09-04.
-- The complete CREATE OR REPLACE FUNCTION definition follows.

CREATE OR REPLACE FUNCTION public.get_work_order_reference_data(p_lab_organization_id uuid)
 RETURNS jsonb
 LANGUAGE plpgsql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
declare
    v_role text := public.effective_lab_role(p_lab_organization_id);
    v_work_types jsonb;
    v_technicians jsonb := '[]'::jsonb;
    v_prices jsonb := '[]'::jsonb;
    v_partners jsonb := '[]'::jsonb;
begin
    if v_role is null then
        raise exception 'Access denied';
    end if;

    select coalesce(
        jsonb_agg(
            jsonb_build_object(
                'id', wt.id,
                'tip_lucrare', wt.tip_lucrare,
                'active', wt.active,
                'billing_mode', wt.billing_mode,
                'processing_enabled', wt.processing_enabled
            )
            order by wt.tip_lucrare, wt.id
        ),
        '[]'::jsonb
    )
    into v_work_types
    from public.lab_work_types wt
    where wt.lab_organization_id = p_lab_organization_id
      and wt.active = true;

    if v_role in ('admin','manager','dashboard') then
        select coalesce(
            jsonb_agg(
                jsonb_build_object(
                    'username', p.username,
                    'display_name', p.display_name,
                    'technician_name', p.technician_name
                )
                order by coalesce(p.technician_name,p.display_name,p.username)
            ),
            '[]'::jsonb
        )
        into v_technicians
        from public.organization_memberships m
        join public.profiles p
          on p.id = m.user_id
        where m.organization_id = p_lab_organization_id
          and m.status = 'active'::public.membership_status
          and lower(m.role) = 'technician'
          and p.active = true;
    end if;

    if v_role in ('admin','manager') then
        select coalesce(
            jsonb_agg(
                jsonb_build_object(
                    'id', cp.id,
                    'contract', cp.contract,
                    'tip_lucrare', cp.tip_lucrare,
                    'pret', cp.pret
                )
                order by cp.contract, cp.tip_lucrare, cp.id
            ),
            '[]'::jsonb
        )
        into v_prices
        from public.lab_contract_work_prices cp
        where cp.lab_organization_id = p_lab_organization_id;
    end if;

    -- Doctors keep their account partner; do not disclose other clinic names.
    if v_role in ('admin','manager','technician','dashboard') then
        select coalesce(jsonb_agg(jsonb_build_object(
            'id', p.id, 'name', p.name, 'active', p.active
        ) order by p.name), '[]'::jsonb)
        into v_partners
        from public.lab_partners p
        where p.lab_organization_id = p_lab_organization_id
          and (p.active or v_role = 'admin');
    end if;

    return jsonb_build_object(
        'role', v_role,
        'work_types', v_work_types,
        'technicians', v_technicians,
        'contract_prices', v_prices,
        'partners', v_partners
    );
end;
$function$
;

-- Security definer: True
-- Return type: jsonb
-- Identity arguments: p_lab_organization_id uuid

-- Include linked Lab Partner accounts among authorized approval recipients.
CREATE OR REPLACE FUNCTION public.email_notification_recipient_allowed(p_user uuid,p_lab uuid,p_order bigint,p_kind text,p_stage text)
RETURNS boolean LANGUAGE sql STABLE SECURITY DEFINER SET search_path='' AS $$
 SELECT EXISTS (
 SELECT 1 FROM public.profiles p JOIN public.lab_work_orders w ON w.lab_organization_id=p_lab AND w.id=p_order
 WHERE p.id=p_user AND p.active AND w.archived_at IS NULL
 AND p_kind IN ('new_work_order','work_order_status','assignment','approval_state')
 AND CASE WHEN p_kind='work_order_status' THEN p.notify_stage_status ELSE p.notify_new_work_order END
 AND (
  (p_kind<>'assignment' AND EXISTS(SELECT 1 FROM public.organization_memberships m WHERE m.organization_id=p_lab AND m.user_id=p.id AND m.status='active' AND lower(m.role) IN ('admin','manager')))
  OR (
   EXISTS(SELECT 1 FROM public.organization_memberships m WHERE m.organization_id=p_lab AND m.user_id=p.id AND m.status='active' AND lower(m.role)='technician')
   AND nullif(trim(p.technician_name),'') IS NOT NULL
   -- Ambiguous names must not route a private notification to multiple accounts.
   AND 1=(SELECT count(*) FROM public.profiles p2 JOIN public.organization_memberships m2 ON m2.user_id=p2.id AND m2.organization_id=p_lab AND m2.status='active' AND lower(m2.role)='technician' WHERE p2.active AND lower(trim(p2.technician_name))=lower(trim(p.technician_name)))
   AND EXISTS(SELECT 1 FROM (VALUES
    ('model',w.tehnician_model,w.model_not_applicable),('modelare',w.tehnician1_modelare,w.modelare_not_applicable),('cer_fin',w.tehnician2_cer_fin,w.cer_fin_not_applicable)
   ) s(stage,technician,not_applicable) WHERE NOT coalesce(s.not_applicable,false) AND (p_stage IS NULL OR s.stage=p_stage) AND lower(trim(s.technician))=lower(trim(p.technician_name)))
  )
  OR (p_kind<>'assignment' AND nullif(trim(w.nume_partener),'') IS NOT NULL
   AND lower(trim(w.nume_partener)) IN (lower(trim(p.legacy_partner_name)),lower(trim(p.display_name)),lower(trim(p.legacy_user_id)))
   AND EXISTS(SELECT 1 FROM public.organization_memberships m JOIN public.organizations clinic ON clinic.id=m.organization_id AND clinic.organization_type='clinic'
    JOIN public.organization_relationships r ON r.clinic_organization_id=m.organization_id AND r.lab_organization_id=p_lab AND r.status='active'
    WHERE m.user_id=p.id AND m.status='active' AND lower(m.role)='doctor')
  )
  OR (p_kind='approval_state' AND EXISTS(
   SELECT 1 FROM public.lab_partner_user_links link
   JOIN public.organization_memberships m ON m.organization_id=link.lab_organization_id
    AND m.user_id=link.user_id AND m.status='active' AND lower(m.role) IN ('lab partner','lab_partner')
   JOIN public.lab_partners partner ON partner.id=link.partner_id
    AND partner.lab_organization_id=link.lab_organization_id AND partner.active
   WHERE link.lab_organization_id=p_lab AND link.user_id=p.id AND link.partner_id=w.partner_id
  ))
 ));
$$;
REVOKE ALL ON FUNCTION public.email_notification_recipient_allowed(uuid,uuid,bigint,text,text) FROM PUBLIC,anon,authenticated,service_role;


-- Keep the legacy Doctor edit RPC behind the review lifecycle.
CREATE OR REPLACE FUNCTION public.update_doctor_work_order(p_lab_organization_id uuid, p_work_order_id bigint, p_deadline date, p_nume_pacient text, p_items jsonb, p_case jsonb DEFAULT '{}'::jsonb)
 RETURNS boolean
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
declare
    v_order public.lab_work_orders%rowtype;
begin
    if not public.is_connected_doctor_for_lab(p_lab_organization_id) then
        raise exception 'Doctor access denied';
    end if;

    select *
      into v_order
    from public.lab_work_orders
    where lab_organization_id = p_lab_organization_id
      and id = p_work_order_id
    for update;

    if not found or not public.doctor_matches_partner(v_order.nume_partener) then
        raise exception 'Work Order access denied';
    end if;

    if v_order.order_origin='doctor' and v_order.approval_state<>'rejected' then
        raise exception 'Only rejected Doctor orders can be edited and resubmitted';
    end if;

    if v_order.locked then
        raise exception 'Work Order is locked';
    end if;

    if lower(trim(coalesce(v_order.status,''))) <> 'not started' then
        raise exception 'Doctor can edit only Not Started Work Orders';
    end if;

    if trim(coalesce(p_nume_pacient,'')) = '' then
        raise exception 'Nume_Pacient is required';
    end if;

    update public.lab_work_orders
    set
        deadline = p_deadline,
        nume_pacient = trim(p_nume_pacient),
        updated_by_user_id = public.current_legacy_user_id(),
        updated_at = now()
    where lab_organization_id = p_lab_organization_id
      and id = p_work_order_id;

    perform public.replace_work_order_items(p_lab_organization_id,p_work_order_id,p_items,'General');
    perform public.save_work_order_clinical_case(p_lab_organization_id,p_work_order_id,p_case);
    return true;
end;
$function$
;

-- Show frozen urgency and review metadata on the clinical price sheet.
CREATE OR REPLACE FUNCTION public.get_work_order_price_lines(p_lab uuid,p_order bigint)
RETURNS jsonb
LANGUAGE plpgsql STABLE SECURITY DEFINER
SET search_path=public
AS $$
DECLARE
    v_role text := public.effective_lab_role(p_lab);
    v_result jsonb;
BEGIN
    IF coalesce(v_role,'') NOT IN ('admin','manager','doctor') THEN
        RAISE EXCEPTION 'Price line access denied';
    END IF;
    IF NOT EXISTS (
        SELECT 1 FROM public.lab_work_orders wo
        WHERE wo.lab_organization_id=p_lab AND wo.id=p_order
    ) THEN RAISE EXCEPTION 'Work Order not found'; END IF;
    IF v_role='doctor' AND NOT public.can_access_work_order(p_lab,p_order) THEN
        RAISE EXCEPTION 'Price line access denied';
    END IF;

    SELECT jsonb_build_object(
        'lines',coalesce((
            SELECT jsonb_agg(jsonb_build_object(
                'work_type',line.work_type,'billing_mode',line.billing_mode,
                'billing_scope',line.billing_scope,'quantity',line.quantity,
                'contract',line.contract,'unit_price',line.unit_price,
                'subtotal',line.line_total,'base_subtotal',line.base_line_total,
                'urgent_percent',line.urgent_percent,'urgency_surcharge',line.urgency_surcharge,
                'matched',line.unit_price IS NOT NULL,
                'price_source',line.price_source,'price_fixed_at',line.price_fixed_at,
                'price_migrated',line.price_migrated
            ) ORDER BY line.work_type,line.billing_scope)
            FROM public.lab_work_order_price_lines line
            WHERE line.lab_organization_id=p_lab AND line.work_order_id=p_order
        ),'[]'::jsonb),
        'element_count',coalesce((
            SELECT count(*) FROM public.lab_work_order_items item
            WHERE item.lab_organization_id=p_lab AND item.work_order_id=p_order
        ),0),
        'billing_unit_count',coalesce((
            SELECT sum(line.quantity) FROM public.lab_work_order_price_lines line
            WHERE line.lab_organization_id=p_lab AND line.work_order_id=p_order
        ),0),
        'list_price',wo.snapshot_list_price,'discount',wo.discount,
        'final_price',wo.snapshot_final_price,'partner_name',wo.nume_partener,
        'deadline_at',wo.deadline_at,'approval_state',wo.approval_state,
        'approval_reason',wo.approval_reason
    ) INTO v_result
    FROM public.lab_work_orders wo
    WHERE wo.lab_organization_id=p_lab AND wo.id=p_order;
    RETURN v_result;
END;
$$;

REVOKE ALL ON FUNCTION public.get_work_order_price_lines(uuid,bigint) FROM public,anon;
GRANT EXECUTE ON FUNCTION public.get_work_order_price_lines(uuid,bigint) TO authenticated;
