import test from 'node:test';import assert from 'node:assert/strict';
import {createAdminStorageCleanupHandler} from '../../db/edge-functions/admin-storage-cleanup/handler.mjs';
const env={SUPABASE_URL:'https://abcdefghijklmnopqrst.supabase.co',SUPABASE_ANON_KEY:'anon',SUPABASE_SERVICE_ROLE_KEY:'service'};
function setup({valid=true,active=true,role='Admin',rpcError=false}={}){const calls=[];const query=table=>{const q={select:()=>q,eq:()=>q,maybeSingle:async()=>({data:table==='profiles'?{active}:table==='organizations'?{id:'lab'}:{role,status:'active'}})};return q;};const client={auth:{getUser:async()=>valid?{data:{user:{id:'user'}}}:{error:{message:'bad'}}},from:query,rpc:async(name,p)=>{calls.push({name,p});return rpcError?{error:{message:'Access denied'}}:{data:name==='admin_storage_usage'?{used_bytes:'120000000000',buckets:[],measured_at:'now'}:{id:'job',state:'preview'}};}};return {calls,handle:createAdminStorageCleanupHandler({getEnv:n=>env[n],createClient:()=>client,fetch:async()=>new Response('',{status:500})})};}
const req=body=>new Request('https://example.test',{method:'POST',headers:{Authorization:'Bearer jwt','Content-Type':'application/json'},body:JSON.stringify(body)});
test('only active Admin sessions can call cleanup',async()=>{for(const opts of [{valid:false},{active:false},{role:'Manager'},{role:'Technician'},{role:'Doctor'},{role:'Dashboard'}]){const b=setup(opts);const r=await b.handle(req({operation:'preview',action:'all',from:'2026-10-01',to:'2026-10-01'}));assert.ok([401,403].includes(r.status));assert.equal(b.calls.length,0);}});
test('usage preserves files and shows missing disk configuration',async()=>{const b=setup();const out=await (await b.handle(req({operation:'usage'}))).json();assert.equal(out.usage.files.used_bytes,'120000000000');assert.equal(out.usage.files.quota_bytes,'100000000000');assert.equal(out.usage.database.available,false);});
test('date, operation and body validation precedes RPC',async()=>{const b=setup();for(const body of [{operation:'preview',action:'all',from:'2026-02-30',to:'2026-03-01'},{operation:'preview',action:'files',from:'2026-10-02',to:'2026-10-01'},{operation:'unknown'}]){assert.equal((await b.handle(req(body))).status,400);}assert.equal(b.calls.length,0);const response=await b.handle(new Request('https://test',{method:'POST',headers:{Authorization:'Bearer jwt'},body:'{'}));assert.equal(response.status,400);});
test('preflight and method handling; missing JWT rejected',async()=>{const b=setup();assert.equal((await b.handle(new Request('https://test',{method:'OPTIONS'}))).status,200);assert.equal((await b.handle(new Request('https://test'))).status,405);assert.equal((await b.handle(new Request('https://test',{method:'POST',body:'{}'}))).status,401);});
test('SQL ownership denial is preserved without leaking raw error',async()=>{const b=setup({rpcError:true});const r=await b.handle(req({operation:'status',job_id:'00000000-0000-0000-0000-000000000001'}));assert.equal(r.status,403);});
