'use strict';
// The RO/EN split is a build step, and a build step that silently half-works
// is worse than none: a page that still carries both languages looks correct
// in a browser (the CSS that used to hide one language is gone, so you would
// SEE the duplication) but a page with a broken hreflang set, a canonical
// pointing at the wrong language, or a language link that leads to itself all
// look completely fine to a human and are wrong only to a crawler.
//
// So these assert the things you cannot see: reciprocity, self-consistency,
// and the two textual assumptions the stripper in tools/build-site.js relies
// on to be safe.

const test = require('node:test');
const assert = require('node:assert');
const fs = require('fs');
const path = require('path');

const SRC = path.join(__dirname, '..', 'site-src');
const SITE = path.join(__dirname, '..', 'website');

const PAGES = [
  { file: 'index.html', lang: 'ro', url: 'https://adaptivetech.ro/', pair: 'https://adaptivetech.ro/en/' },
  { file: 'en/index.html', lang: 'en', url: 'https://adaptivetech.ro/en/', pair: 'https://adaptivetech.ro/' },
  {
    file: 'politica-de-confidentialitate.html', lang: 'ro',
    url: 'https://adaptivetech.ro/politica-de-confidentialitate.html',
    pair: 'https://adaptivetech.ro/en/privacy-policy.html',
  },
  {
    file: 'en/privacy-policy.html', lang: 'en',
    url: 'https://adaptivetech.ro/en/privacy-policy.html',
    pair: 'https://adaptivetech.ro/politica-de-confidentialitate.html',
  },
];

const read = (f) => fs.readFileSync(path.join(SITE, f), 'utf8');
const langToggle = (s) => (s.match(/<div class="lang-toggle"[\s\S]*?<\/div>/) || [''])[0];

for (const page of PAGES) {
  const other = page.lang === 'ro' ? 'en' : 'ro';

  test(page.file + ' carries only ' + page.lang, () => {
    const s = read(page.file);
    assert.ok(!s.includes('data-' + other),
      page.file + ' still contains data-' + other + ' -- both languages would be indexed');
    assert.match(s, new RegExp('<html lang="' + page.lang + '">'));
  });

  test(page.file + ' has no runtime language machinery left', () => {
    const s = read(page.file);
    // Each of these existing means the page is still trying to switch language
    // client-side, which is exactly what the split replaced.
    for (const ghost of ['setLang', 'adaptive-lang', '<!--LANG-TOGGLE-->']) {
      assert.ok(!s.includes(ghost), page.file + ' still contains ' + ghost);
    }
  });

  test(page.file + ' declares a reciprocal hreflang set', () => {
    const s = read(page.file);
    const alts = [...s.matchAll(/<link rel="alternate" hreflang="([a-z-]+)" href="([^"]+)" \/>/g)]
      .map((m) => [m[1], m[2]]);
    const byLang = Object.fromEntries(alts);

    assert.strictEqual(alts.length, 3, 'expected ro, en and x-default');
    assert.strictEqual(byLang[page.lang], page.url, 'must point at itself for its own language');
    assert.strictEqual(byLang[other], page.pair, 'must point at its translation');
    // x-default sends unmatched locales to Romanian: a Romanian company
    // selling in Romania, so that is the right default landing.
    assert.strictEqual(byLang['x-default'], PAGES.find((p) => p.lang === 'ro' &&
      (p.pair === page.url || p.url === page.url)).url);

    const canonical = (s.match(/<link rel="canonical" href="([^"]+)" \/>/) || [])[1];
    assert.strictEqual(canonical, page.url, 'canonical must be self-referencing');
  });

  test(page.file + ' language switch points at the other language', () => {
    // The regression this guards: the toggle used to be injected BEFORE the
    // EN link rewrites, so the rewrite rules captured the toggle's own RO
    // link and the EN privacy page offered "RO" as a link to itself. Nothing
    // about that is visible on the page.
    const toggle = langToggle(read(page.file));
    assert.ok(toggle, 'no language toggle found');
    const hrefs = Object.fromEntries(
      [...toggle.matchAll(/id="lang-(ro|en)"[^>]*href="([^"]+)"/g)].map((m) => [m[1], m[2]]));
    assert.strictEqual(hrefs[page.lang], new URL(page.url).pathname, 'self link');
    assert.strictEqual(hrefs[other], new URL(page.pair).pathname, 'link to the translation');
    assert.notStrictEqual(hrefs.ro, hrefs.en, 'the two language links must differ');
  });

  test(page.file + ' is stamped as generated', () => {
    assert.match(read(page.file), /GENERATED by tools\/build-site\.js/);
  });
}

test('EN pages do not link back into the RO tree', () => {
  for (const page of PAGES.filter((p) => p.lang === 'en')) {
    const s = read(page.file);
    // The language toggle is excluded: linking to the RO page is its purpose.
    const body = s.replace(/<div class="lang-toggle"[\s\S]*?<\/div>/, '');
    for (const href of body.match(/href="\/[^"]*"/g) || []) {
      // The demo is one bilingual app, not a translated page: it keeps its
      // single URL and is handed the language in the query string.
      if (href === 'href="/demo/?lang=en"') continue;
      assert.ok(href.startsWith('href="/en/'),
        page.file + ' links out of the EN tree: ' + href);
    }
  }
});

test('sitemap lists exactly the built pages', () => {
  const xml = fs.readFileSync(path.join(SITE, 'sitemap.xml'), 'utf8');
  const locs = [...xml.matchAll(/<loc>([^<]+)<\/loc>/g)].map((m) => m[1]).sort();
  assert.deepStrictEqual(locs, PAGES.map((p) => p.url).sort());
  // The demo is noindex; listing it here would be a contradiction Search
  // Console reports as an error. Checked against the URLs, not the raw file --
  // the generated comment says the word /demo/ to explain its own absence.
  const urls = [...xml.matchAll(/(?:<loc>|href=")([^<"]+)/g)].map((m) => m[1]);
  assert.ok(!urls.some((u) => u.includes('/demo/')), 'a noindex URL must not be in the sitemap');
});

// ── The two assumptions tools/build-site.js relies on to strip a language
//    safely. Both hold today; either breaking would corrupt output silently,
//    so they are asserted against the MASTERS rather than the build.
for (const master of ['index.html', 'politica-de-confidentialitate.html']) {
  test(master + ': no language span contains a nested <span>', () => {
    // The stripper matches non-greedily to the first </span>. A nested span
    // would end the match early and leave orphan markup behind.
    const s = fs.readFileSync(path.join(SRC, master), 'utf8');
    const re = /<span data-(?:ro|en)\b[^>]*>([\s\S]*?)<\/span>/g;
    let m, nested = 0;
    while ((m = re.exec(s))) if (m[1].includes('<span')) nested++;
    assert.strictEqual(nested, 0);
  });

  test(master + ': no language span sits flush against text', () => {
    // The stripper deliberately does not consume surrounding whitespace, so a
    // span touching a letter on either side would weld two words together
    // when the other language is removed.
    const s = fs.readFileSync(path.join(SRC, master), 'utf8');
    const re = /<span data-(?:ro|en)\b[^>]*>[\s\S]*?<\/span>/g;
    let m; const flush = [];
    while ((m = re.exec(s))) {
      const before = s[m.index - 1] || '';
      const after = s[m.index + m[0].length] || '';
      if (/[\p{L}\p{N}]/u.test(before) || /[\p{L}\p{N}]/u.test(after)) {
        flush.push(s.slice(m.index - 30, m.index + m[0].length + 30));
      }
    }
    assert.deepStrictEqual(flush, []);
  });
}
