-- ---------------------------------------------------------------------
-- Rebuilds the whole schema, in dependency order.
--
--   psql "$DATABASE_URL" -v ON_ERROR_STOP=1 -f db/schema/apply.sql
--
-- Run from the repository root: the \i paths are relative to it.
--
-- GENERATED by tools/build-db-apply.js -- do not edit by hand.
-- Every file it includes is idempotent, so this is safe to re-run.
-- ---------------------------------------------------------------------

\set ON_ERROR_STOP on
begin;

-- LANGUAGE sql function bodies are validated at CREATE time, and these
-- functions call one another in no particular order. Deferring the check
-- is what pg_restore does, for the same reason.
set local check_function_bodies = off;

\echo == 00 prerequisites: extensions and enum types ==
\i db/schema/00_prerequisites.sql

\echo == 10 tables: structure, constraints, indexes, RLS enabled ==
\i db/schema/10_tables/01_profiles.sql
\i db/schema/10_tables/02_chat_threads.sql
\i db/schema/10_tables/03_chat_messages.sql
\i db/schema/10_tables/04_chat_attachments.sql
\i db/schema/10_tables/05_chat_thread_participants.sql
\i db/schema/10_tables/06_organizations.sql
\i db/schema/10_tables/07_lab_calendar_events.sql
\i db/schema/10_tables/08_lab_chat_history.sql
\i db/schema/10_tables/09_lab_contract_work_prices.sql
\i db/schema/10_tables/10_lab_materials_inventory.sql
\i db/schema/10_tables/11_lab_patient_cases.sql
\i db/schema/10_tables/12_lab_profiles.sql
\i db/schema/10_tables/13_lab_public_offers.sql
\i db/schema/10_tables/14_lab_technician_costs.sql
\i db/schema/10_tables/15_lab_work_orders.sql
\i db/schema/10_tables/16_lab_work_types.sql
\i db/schema/10_tables/17_legacy_user_directory.sql
\i db/schema/10_tables/18_organization_memberships.sql
\i db/schema/10_tables/19_organization_relationships.sql
\i db/schema/10_tables/20_relationship_prices.sql
\i db/schema/10_tables/21_relationship_terms.sql
\i db/schema/10_tables/22_role_permissions.sql
\i db/schema/10_tables/23_work_order_files.sql
\i db/schema/10_tables/24_work_order_items.sql
\i db/schema/10_tables/25_work_order_stage_assignments.sql
\i db/schema/10_tables/26_technician_payments.sql
\i db/schema/10_tables/27_work_order_financial_audit.sql

\echo == 20 functions ==
\i db/schema/20_functions/admin_bulk_config_import.sql
\i db/schema/20_functions/admin_clear_ai_history_older_than_30_days.sql
\i db/schema/20_functions/admin_clear_chat_messages_older_than_30_days.sql
\i db/schema/20_functions/ai_mutate_work_order.sql
\i db/schema/20_functions/ai_mutate_work_order_role_safe.sql
\i db/schema/20_functions/ai_read_dataset.sql
\i db/schema/20_functions/ai_read_datasets.sql
\i db/schema/20_functions/ai_technician_receivables.sql
\i db/schema/20_functions/ai_technician_work_orders.sql
\i db/schema/20_functions/ai_technician_work_types.sql
\i db/schema/20_functions/append_my_chat_message.sql
\i db/schema/20_functions/backfill_work_order_financial_history.sql
\i db/schema/20_functions/can_access_work_order.sql
\i db/schema/20_functions/chat_can_message.sql
\i db/schema/20_functions/chat_can_message_as.sql
\i db/schema/20_functions/chat_cleanup_preview.sql
\i db/schema/20_functions/chat_clear_older_than_30_days.sql
\i db/schema/20_functions/chat_create_group.sql
\i db/schema/20_functions/chat_get_messages.sql
\i db/schema/20_functions/chat_get_thread_members.sql
\i db/schema/20_functions/chat_is_thread_participant.sql
\i db/schema/20_functions/chat_list_threads.sql
\i db/schema/20_functions/chat_mark_read.sql
\i db/schema/20_functions/chat_open_direct_thread.sql
\i db/schema/20_functions/chat_search_users.sql
\i db/schema/20_functions/chat_send_message.sql
\i db/schema/20_functions/chat_users_can_share_thread.sql
\i db/schema/20_functions/connected_clinic_for_lab.sql
\i db/schema/20_functions/create_technician_work_order.sql
\i db/schema/20_functions/create_work_order.sql
\i db/schema/20_functions/current_legacy_user_id.sql
\i db/schema/20_functions/current_org_role.sql
\i db/schema/20_functions/current_partner_name.sql
\i db/schema/20_functions/current_technician_name.sql
\i db/schema/20_functions/delete_doctor_work_order.sql
\i db/schema/20_functions/delete_management_work_order.sql
\i db/schema/20_functions/doctor_matches_partner.sql
\i db/schema/20_functions/effective_lab_role.sql
\i db/schema/20_functions/enforce_work_order_stage_rules.sql
\i db/schema/20_functions/estimate_doctor_work_order_price.sql
\i db/schema/20_functions/estimate_work_order_items.sql
\i db/schema/20_functions/get_ai_bootstrap.sql
\i db/schema/20_functions/get_ai_context.sql
\i db/schema/20_functions/get_app_identity.sql
\i db/schema/20_functions/get_flowrise_lab_id.sql
\i db/schema/20_functions/get_my_chat_history.sql
\i db/schema/20_functions/get_my_production.sql
\i db/schema/20_functions/get_my_salary.sql
\i db/schema/20_functions/get_my_work_orders.sql
\i db/schema/20_functions/get_my_work_orders_v188.sql
\i db/schema/20_functions/get_patient_case.sql
\i db/schema/20_functions/get_work_order_financial_history.sql
\i db/schema/20_functions/get_work_order_reference_data.sql
\i db/schema/20_functions/has_org_role.sql
\i db/schema/20_functions/has_role_permission.sql
\i db/schema/20_functions/is_active_org_member.sql
\i db/schema/20_functions/is_connected_doctor_for_lab.sql
\i db/schema/20_functions/is_lab_dashboard.sql
\i db/schema/20_functions/is_lab_management.sql
\i db/schema/20_functions/is_lab_technician.sql
\i db/schema/20_functions/is_org_member.sql
\i db/schema/20_functions/next_lab_work_order_id.sql
\i db/schema/20_functions/organization_is_type.sql
\i db/schema/20_functions/record_technician_payment.sql
\i db/schema/20_functions/replace_work_order_items.sql
\i db/schema/20_functions/resolve_effective_work_order_contract.sql
\i db/schema/20_functions/resolve_work_order_price_snapshot.sql
\i db/schema/20_functions/reverse_technician_payment.sql
\i db/schema/20_functions/save_my_work_order_case.sql
\i db/schema/20_functions/set_stage_payment_status.sql
\i db/schema/20_functions/set_updated_at.sql
\i db/schema/20_functions/set_work_order_lock.sql
\i db/schema/20_functions/set_work_order_price_snapshot.sql
\i db/schema/20_functions/set_work_order_status.sql
\i db/schema/20_functions/sync_work_order_stage_assignment.sql
\i db/schema/20_functions/update_doctor_work_order.sql
\i db/schema/20_functions/update_management_work_order.sql
\i db/schema/20_functions/update_material_quantity.sql
\i db/schema/20_functions/update_my_stage_status.sql
\i db/schema/20_functions/upsert_patient_case.sql

\echo == 30 policies, triggers, function-dependent constraints ==
\i db/schema/30_policies/01_profiles.sql
\i db/schema/30_policies/02_chat_threads.sql
\i db/schema/30_policies/03_chat_messages.sql
\i db/schema/30_policies/04_chat_attachments.sql
\i db/schema/30_policies/05_chat_thread_participants.sql
\i db/schema/30_policies/06_organizations.sql
\i db/schema/30_policies/07_lab_calendar_events.sql
\i db/schema/30_policies/08_lab_chat_history.sql
\i db/schema/30_policies/09_lab_contract_work_prices.sql
\i db/schema/30_policies/10_lab_materials_inventory.sql
\i db/schema/30_policies/11_lab_patient_cases.sql
\i db/schema/30_policies/12_lab_profiles.sql
\i db/schema/30_policies/13_lab_public_offers.sql
\i db/schema/30_policies/14_lab_technician_costs.sql
\i db/schema/30_policies/15_lab_work_orders.sql
\i db/schema/30_policies/16_lab_work_types.sql
\i db/schema/30_policies/17_legacy_user_directory.sql
\i db/schema/30_policies/18_organization_memberships.sql
\i db/schema/30_policies/19_organization_relationships.sql
\i db/schema/30_policies/20_relationship_prices.sql
\i db/schema/30_policies/21_relationship_terms.sql
\i db/schema/30_policies/22_role_permissions.sql
\i db/schema/30_policies/23_work_order_files.sql
\i db/schema/30_policies/24_work_order_items.sql
\i db/schema/30_policies/25_work_order_stage_assignments.sql
\i db/schema/30_policies/26_technician_payments.sql
\i db/schema/30_policies/27_work_order_financial_audit.sql

\echo == 40 grants ==
\i db/schema/40_grants.sql

\echo == 50 storage buckets ==
\i db/schema/50_storage.sql

commit;
