const test=require('node:test'),assert=require('node:assert/strict');
const {chartModel,formatBytes,createController,clinicalDraftState,escapeHtml}=require('../../website/app/storage-cleanup.js');
test('decimal GB and bigint values retain precision',()=>{assert.equal(formatBytes('100000000000'),'100,00 GB');assert.equal(formatBytes('1000000000'),'1,00 GB');assert.equal(chartModel({used_bytes:'120000000000',total_bytes:'100000000000'}).usedPercent,120);const m=chartModel({used_bytes:'120000000000',total_bytes:'100000000000'});assert.equal(m.free_bytes,'0');assert.equal(m.overage_bytes,'20000000000');assert.equal(m.drawPercent,100);assert.equal(chartModel({used_bytes:'0',total_bytes:'0'}),null);});
test('disk availability uses actual available bytes, including reserved space',()=>{const m=chartModel({used_bytes:'600',total_bytes:'1000',available_bytes:'350'});assert.equal(m.freePercent,35);assert.equal(m.free_bytes,'350');assert.equal(chartModel({used_bytes:'-1',total_bytes:'100'}),null);assert.equal(chartModel({available:false}),null);});
test('confirmed clinical purge suppresses automatic item reconstruction and preserves generation',()=>{assert.deepEqual(clinicalDraftState({clinical_cleared_at:'now',clinical_cleanup_generation:'2'},[{tooth_number:11}]),{cleared:true,items:[],expected_cleanup_revision:'2'});assert.equal(clinicalDraftState({clinical_cleanup_generation:'2'},[{tooth_number:11}]).items.length,1);});
test('output names and identifiers are escaped',()=>assert.equal(escapeHtml('<script>"&'), '&lt;script&gt;&quot;&amp;'));
function backend(){const calls=[];const request=async(op,p)=>{calls.push({op,p});return op==='preview'?{job:{id:'job',action:p.action,state:'preview',progress:{total:1},from:p.from,to:p.to}}:op==='status'?{job:{id:p.job_id,state:'running'},orders:[{order_id:'9007199254740993'}],total:1}:op==='jobs'?{jobs:[]}:op==='usage'?{usage:{files:{used_bytes:'0'}}}:{job:{id:p.job_id,action:'all',state:op==='process'?'completed':'running',progress:{completed:1}}};};return {calls,request};}
test('three independent previews use the same dates and invalidate on date change',async()=>{const b=backend(),c=createController({request:b.request});c.setDates('2026-10-01','2026-10-02');for(const action of ['files','clinical','all']){await c.preview(action);assert.equal(c.state.preview.action,action);}assert.deepEqual(b.calls.filter(x=>x.op==='preview').map(x=>x.p.action),['files','clinical','all']);assert.equal(c.state.page.orders[0].order_id,'9007199254740993');c.setDates('2026-10-02','2026-10-03');assert.equal(c.state.preview,null);await assert.rejects(c.confirm('ȘTERGE'));});
test('complete purge requires exact confirmation and blocks double submissions',async()=>{const b=backend(),c=createController({request:b.request});c.setDates('2026-10-01','2026-10-02');await c.preview('all');await assert.rejects(c.confirm('wrong'));const promise=c.confirm('ȘTERGE');await c.confirm('ȘTERGE');await promise;assert.equal(b.calls.filter(x=>x.op==='confirm').length,1);assert.equal(c.state.job.state,'completed');});
test('destroy prevents late results and callbacks after logout',async()=>{let finish,changed=0;const c=createController({request:()=>new Promise(resolve=>finish=resolve),onChange:()=>changed++});const p=c.refresh();c.destroy();const before=changed;finish({usage:{files:{used_bytes:'123'}}});await p;assert.equal(changed,before);assert.equal(c.state.usage,null);});
test('missing interval cannot start deletion preview',async()=>{const b=backend(),c=createController({request:b.request});await assert.rejects(c.preview('files'));assert.match(c.state.error,/interval/);assert.equal(b.calls.length,0);});
test('date changes do not discard independent usage measurements',async()=>{let finish;const c=createController({request:()=>new Promise(resolve=>finish=resolve)});const p=c.refresh();c.setDates('2026-01-01','2026-01-31');finish({usage:{files:{used_bytes:'123'}}});await p;assert.equal(c.state.usage.files.used_bytes,'123');});
test('cleanup invalidates drafts when every initial batch has finished',async()=>{let result,cleared=0;const c=createController({request:async()=>({job:result}),onClinicalCleared:()=>cleared++});c.state.job={id:'job',action:'clinical',state:'running'};result={...c.state.job,progress:{completed:1,total:2}};await c.tick(true);assert.equal(cleared,0);result={...result,state:'completed',progress:{completed:2,total:2}};await c.tick();assert.equal(cleared,1);await c.tick();assert.equal(cleared,1);});
