#!/usr/bin/env python3
"""Expand db/schema/apply.sql into one Supabase SQL Editor compatible file."""

from pathlib import Path
import sys


ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "db/schema/apply.sql"
OUTPUT = ROOT / "db/schema/apply.supabase.sql"


def build() -> str:
    output = [
        "-- GENERATED by tools/build-supabase-editor-sql.py; do not edit.",
        "-- Paste this entire file into Supabase Dashboard > SQL Editor > New query.",
        "-- Run it once. The surrounding transaction rolls everything back on error.",
        "",
    ]

    for raw_line in SOURCE.read_text().splitlines():
        line = raw_line.strip()
        if line.startswith("\\set "):
            continue
        if line.startswith("\\echo "):
            echo_text = line.removeprefix("\\echo ").strip()
            output.extend(("", f"-- {echo_text}"))
            continue
        if line.startswith("\\i "):
            relative_path = line.removeprefix("\\i ").strip()
            included = ROOT / relative_path
            if not included.is_file():
                raise FileNotFoundError(f"Missing schema include: {relative_path}")
            output.extend(
                (
                    "",
                    f"-- BEGIN {relative_path}",
                    included.read_text().rstrip(),
                    f"-- END {relative_path}",
                )
            )
            continue
        output.append(raw_line)

    return "\n".join(output).rstrip() + "\n"


def main() -> int:
    generated = build()
    if "--check" in sys.argv:
        if not OUTPUT.exists() or OUTPUT.read_text() != generated:
            print(f"{OUTPUT.relative_to(ROOT)} is out of date", file=sys.stderr)
            return 1
        print(f"{OUTPUT.relative_to(ROOT)} is up to date")
        return 0

    OUTPUT.write_text(generated)
    print(f"wrote {OUTPUT.relative_to(ROOT)} ({OUTPUT.stat().st_size} bytes)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
