-- Durable Admin cleanup selections; no patient or financial payload snapshots.
ALTER TABLE public.lab_work_orders
 ADD COLUMN IF NOT EXISTS cleanup_revision bigint NOT NULL DEFAULT 0,
 ADD COLUMN IF NOT EXISTS clinical_cleanup_generation bigint NOT NULL DEFAULT 0,
 ADD COLUMN IF NOT EXISTS clinical_cleared_at timestamptz;
CREATE TABLE IF NOT EXISTS public.admin_cleanup_jobs(
 id uuid PRIMARY KEY DEFAULT gen_random_uuid(), lab_organization_id uuid NOT NULL REFERENCES public.organizations(id),
 created_by uuid NOT NULL, action text NOT NULL CHECK(action IN ('files','clinical','all')),
 date_from date NOT NULL,date_to date NOT NULL CHECK(date_to>=date_from),
 state text NOT NULL DEFAULT 'preview' CHECK(state IN ('preview','running','awaiting_uploads','completed','partial','failed','expired')),
 created_at timestamptz NOT NULL DEFAULT now(), expires_at timestamptz NOT NULL DEFAULT now()+interval '15 minutes',
 confirmed_at timestamptz,reconcile_after timestamptz,updated_at timestamptz NOT NULL DEFAULT now(),
 missing_dates_count integer NOT NULL DEFAULT 0
);
CREATE TABLE IF NOT EXISTS public.admin_cleanup_items(
 id uuid PRIMARY KEY DEFAULT gen_random_uuid(),job_id uuid NOT NULL REFERENCES public.admin_cleanup_jobs(id) ON DELETE CASCADE,
 order_id bigint NOT NULL,revision bigint NOT NULL,
 state text NOT NULL DEFAULT 'pending' CHECK(state IN ('pending','processing','awaiting_uploads','completed','skipped','failed')),
 counts jsonb NOT NULL DEFAULT '{}',bytes bigint NOT NULL DEFAULT 0,worker_id uuid,lease_until timestamptz,
 error_code text,error_message text,initial_finished boolean NOT NULL DEFAULT false,
 UNIQUE(job_id,order_id)
);
CREATE TABLE IF NOT EXISTS public.admin_cleanup_files(
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,item_id uuid NOT NULL REFERENCES public.admin_cleanup_items(id) ON DELETE CASCADE,
 bucket text NOT NULL CHECK(bucket='work-order-files'),object_path text NOT NULL,metadata_id uuid,
 size_bytes bigint,object_version text,initial_done boolean NOT NULL DEFAULT false,reconciled boolean NOT NULL DEFAULT false,
 UNIQUE(item_id,bucket,object_path)
);
CREATE TABLE IF NOT EXISTS public.lab_work_order_id_watermarks(
 lab_organization_id uuid PRIMARY KEY REFERENCES public.organizations(id),maximum_id bigint NOT NULL
);
INSERT INTO public.lab_work_order_id_watermarks SELECT lab_organization_id,max(id) FROM public.lab_work_orders GROUP BY lab_organization_id
ON CONFLICT(lab_organization_id) DO UPDATE SET maximum_id=greatest(lab_work_order_id_watermarks.maximum_id,excluded.maximum_id);
ALTER TABLE public.admin_cleanup_jobs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.admin_cleanup_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.admin_cleanup_files ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.lab_work_order_id_watermarks ENABLE ROW LEVEL SECURITY;
CREATE INDEX IF NOT EXISTS admin_cleanup_jobs_due_idx ON public.admin_cleanup_jobs(state,reconcile_after,created_at);
CREATE INDEX IF NOT EXISTS admin_cleanup_items_job_idx ON public.admin_cleanup_items(job_id,state,order_id);
CREATE INDEX IF NOT EXISTS admin_cleanup_items_order_idx ON public.admin_cleanup_items(order_id,state);

ALTER TABLE public.admin_cleanup_files ADD COLUMN IF NOT EXISTS object_version text;
